<?php
// autogenerated file 17.11.2006 13:29
// $Id: AccessRuleCurrentStatusCodeType.php,v 1.1.1.1 2006/12/22 14:37:10 gswkaiser Exp $
// $Log: AccessRuleCurrentStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:10  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class AccessRuleCurrentStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NotSet
	var $NotSet = 'NotSet';
	// @var string $HourlyLimitExceeded
	var $HourlyLimitExceeded = 'HourlyLimitExceeded';
	// @var string $DailyLimitExceeded
	var $DailyLimitExceeded = 'DailyLimitExceeded';
	// @var string $PeriodicLimitExceeded
	var $PeriodicLimitExceeded = 'PeriodicLimitExceeded';
	// @var string $HourlySoftLimitExceeded
	var $HourlySoftLimitExceeded = 'HourlySoftLimitExceeded';
	// @var string $DailySoftLimitExceeded
	var $DailySoftLimitExceeded = 'DailySoftLimitExceeded';
	// @var string $PeriodicSoftLimitExceeded
	var $PeriodicSoftLimitExceeded = 'PeriodicSoftLimitExceeded';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function AccessRuleCurrentStatusCodeType()
	{
		$this->EbatNs_FacetType('AccessRuleCurrentStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AccessRuleCurrentStatusCodeType = new AccessRuleCurrentStatusCodeType();

?>
