<?php
// autogenerated file 17.11.2006 13:29
// $Id: AccountEntrySortTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:11 gswkaiser Exp $
// $Log: AccountEntrySortTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:11  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class AccountEntrySortTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $AccountEntryCreatedTimeAscending
	var $AccountEntryCreatedTimeAscending = 'AccountEntryCreatedTimeAscending';
	// @var string $AccountEntryCreatedTimeDescending
	var $AccountEntryCreatedTimeDescending = 'AccountEntryCreatedTimeDescending';
	// @var string $AccountEntryItemNumberAscending
	var $AccountEntryItemNumberAscending = 'AccountEntryItemNumberAscending';
	// @var string $AccountEntryItemNumberDescending
	var $AccountEntryItemNumberDescending = 'AccountEntryItemNumberDescending';
	// @var string $AccountEntryFeeTypeAscending
	var $AccountEntryFeeTypeAscending = 'AccountEntryFeeTypeAscending';
	// @var string $AccountEntryFeeTypeDescending
	var $AccountEntryFeeTypeDescending = 'AccountEntryFeeTypeDescending';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function AccountEntrySortTypeCodeType()
	{
		$this->EbatNs_FacetType('AccountEntrySortTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AccountEntrySortTypeCodeType = new AccountEntrySortTypeCodeType();

?>
