<?php
// autogenerated file 17.11.2006 13:29
// $Id: AccountHistorySelectionCodeType.php,v 1.1.1.1 2006/12/22 14:37:12 gswkaiser Exp $
// $Log: AccountHistorySelectionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:12  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class AccountHistorySelectionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $LastInvoice
	var $LastInvoice = 'LastInvoice';
	// @var string $SpecifiedInvoice
	var $SpecifiedInvoice = 'SpecifiedInvoice';
	// @var string $BetweenSpecifiedDates
	var $BetweenSpecifiedDates = 'BetweenSpecifiedDates';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function AccountHistorySelectionCodeType()
	{
		$this->EbatNs_FacetType('AccountHistorySelectionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AccountHistorySelectionCodeType = new AccountHistorySelectionCodeType();

?>
