<?php
// autogenerated file 17.11.2006 13:24
// $Id: AddMemberMessageResponseType.php,v 1.1.1.1 2006/12/22 14:37:13 gswkaiser Exp $
// $Log: AddMemberMessageResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:13  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class AddMemberMessageResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function AddMemberMessageResponseType()
	{
		$this->AbstractResponseType('AddMemberMessageResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
