<?php
// autogenerated file 17.11.2006 13:29
// $Id: AddOrderRequestType.php,v 1.1.1.1 2006/12/22 14:37:14 gswkaiser Exp $
// $Log: AddOrderRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:14  gswkaiser
// no message
//
//
require_once 'OrderType.php';
require_once 'AbstractRequestType.php';

class AddOrderRequestType extends AbstractRequestType
{
	// start props
	// @var OrderType $Order
	var $Order;
	// end props

/**
 *

 * @return OrderType
 */
	function getOrder()
	{
		return $this->Order;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrder($value)
	{
		$this->Order = $value;
	}
/**
 *

 * @return 
 */
	function AddOrderRequestType()
	{
		$this->AbstractRequestType('AddOrderRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Order' =>
				array(
					'required' => false,
					'type' => 'OrderType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
