<?php
// autogenerated file 17.11.2006 13:29
// $Id: AddressOwnerCodeType.php,v 1.1.1.1 2006/12/22 14:37:14 gswkaiser Exp $
// $Log: AddressOwnerCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:14  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class AddressOwnerCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $PayPal
	var $PayPal = 'PayPal';
	// @var string $eBay
	var $eBay = 'eBay';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function AddressOwnerCodeType()
	{
		$this->EbatNs_FacetType('AddressOwnerCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AddressOwnerCodeType = new AddressOwnerCodeType();

?>
