<?php
// autogenerated file 17.11.2006 13:29
// $Id: AddToItemDescriptionResponseType.php,v 1.1.1.1 2006/12/22 14:37:16 gswkaiser Exp $
// $Log: AddToItemDescriptionResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:16  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class AddToItemDescriptionResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function AddToItemDescriptionResponseType()
	{
		$this->AbstractResponseType('AddToItemDescriptionResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
