<?php
// autogenerated file 17.11.2006 13:29
// $Id: AdFormatEnabledCodeType.php,v 1.1.1.1 2006/12/22 14:37:16 gswkaiser Exp $
// $Log: AdFormatEnabledCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:16  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class AdFormatEnabledCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Disabled
	var $Disabled = 'Disabled';
	// @var string $Enabled
	var $Enabled = 'Enabled';
	// @var string $Only
	var $Only = 'Only';
	// @var string $ClassifiedAdEnabled
	var $ClassifiedAdEnabled = 'ClassifiedAdEnabled';
	// @var string $ClassifiedAdOnly
	var $ClassifiedAdOnly = 'ClassifiedAdOnly';
	// end props

/**
 *

 * @return 
 */
	function AdFormatEnabledCodeType()
	{
		$this->EbatNs_FacetType('AdFormatEnabledCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AdFormatEnabledCodeType = new AdFormatEnabledCodeType();

?>
