<?php
// autogenerated file 17.11.2006 13:29
// $Id: AdFormatEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:16 gswkaiser Exp $
// $Log: AdFormatEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:16  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class AdFormatEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function AdFormatEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('AdFormatEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
