<?php
// autogenerated file 17.11.2006 13:29
// $Id: AmountType.php,v 1.1.1.1 2006/12/22 14:37:17 gswkaiser Exp $
// $Log: AmountType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:17  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class AmountType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function AmountType()
	{
		$this->EbatNs_ComplexType('AmountType', 'urn:ebay:apis:eBLBaseComponents');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'currencyID' =>
			array(
				'name' => 'currencyID',
				'type' => 'CurrencyCodeType',
				'use' => 'required'
			)
		));

	}
}
?>
