<?php
// autogenerated file 17.11.2006 13:29
// $Id: AttributeSetType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: AttributeSetType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'AttributeType.php';
require_once 'EbatNs_ComplexType.php';

class AttributeSetType extends EbatNs_ComplexType
{
	// start props
	// @var AttributeType $Attribute
	var $Attribute;
	// end props

/**
 *

 * @return AttributeType
 * @param  $index 
 */
	function getAttribute($index = null)
	{
		if ($index) {
		return $this->Attribute[$index];
	} else {
		return $this->Attribute;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAttribute($value, $index = null)
	{
		if ($index) {
	$this->Attribute[$index] = $value;
	} else {
	$this->Attribute = $value;
	}

	}
/**
 *

 * @return 
 */
	function AttributeSetType()
	{
		$this->EbatNs_ComplexType('AttributeSetType', 'http://www.w3.org/2001/XMLSchema');
		$this->_elements = array_merge($this->_elements,
			array(
				'Attribute' =>
				array(
					'required' => false,
					'type' => 'AttributeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));
	$this->_attributes = array_merge($this->_attributes,
		array(
			'attributeSetID' =>
			array(
				'name' => 'attributeSetID',
				'type' => 'int',
				'use' => 'required'
			),
			'attributeSetVersion' =>
			array(
				'name' => 'attributeSetVersion',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
