<?php
// autogenerated file 17.11.2006 13:29
// $Id: AuthenticationEntryArrayType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: AuthenticationEntryArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AuthenticationEntryType.php';

class AuthenticationEntryArrayType extends EbatNs_ComplexType
{
	// start props
	// @var AuthenticationEntryType $AuthenticationEntry
	var $AuthenticationEntry;
	// end props

/**
 *

 * @return AuthenticationEntryType
 * @param  $index 
 */
	function getAuthenticationEntry($index = null)
	{
		if ($index) {
		return $this->AuthenticationEntry[$index];
	} else {
		return $this->AuthenticationEntry;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAuthenticationEntry($value, $index = null)
	{
		if ($index) {
	$this->AuthenticationEntry[$index] = $value;
	} else {
	$this->AuthenticationEntry = $value;
	}

	}
/**
 *

 * @return 
 */
	function AuthenticationEntryArrayType()
	{
		$this->EbatNs_ComplexType('AuthenticationEntryArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AuthenticationEntry' =>
				array(
					'required' => false,
					'type' => 'AuthenticationEntryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
