<?php
// autogenerated file 17.11.2006 13:29
// $Id: BalanceCodeType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: BalanceCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class BalanceCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Other
	var $Other = 'Other';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BalanceCodeType()
	{
		$this->EbatNs_FacetType('BalanceCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BalanceCodeType = new BalanceCodeType();

?>
