<?php
// autogenerated file 17.11.2006 13:29
// $Id: BestOfferTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:19 gswkaiser Exp $
// $Log: BestOfferTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:19  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class BestOfferTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $BuyerBestOffer
	var $BuyerBestOffer = 'BuyerBestOffer';
	// @var string $BuyerCounterOffer
	var $BuyerCounterOffer = 'BuyerCounterOffer';
	// @var string $SellerCounterOffer
	var $SellerCounterOffer = 'SellerCounterOffer';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BestOfferTypeCodeType()
	{
		$this->EbatNs_FacetType('BestOfferTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BestOfferTypeCodeType = new BestOfferTypeCodeType();

?>
