<?php
// autogenerated file 17.11.2006 13:29
// $Id: BestOfferIDType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: BestOfferIDType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'EbatNs_SimpleType.php';

class BestOfferIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function BestOfferIDType()
	{
		$this->EbatNs_SimpleType('BestOfferIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BestOfferIDType = new BestOfferIDType();

?>
