<?php
// autogenerated file 17.11.2006 13:29
// $Id: BestOfferArrayType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: BestOfferArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'BestOfferType.php';

class BestOfferArrayType extends EbatNs_ComplexType
{
	// start props
	// @var BestOfferType $BestOffer
	var $BestOffer;
	// end props

/**
 *

 * @return BestOfferType
 * @param  $index 
 */
	function getBestOffer($index = null)
	{
		if ($index) {
		return $this->BestOffer[$index];
	} else {
		return $this->BestOffer;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setBestOffer($value, $index = null)
	{
		if ($index) {
	$this->BestOffer[$index] = $value;
	} else {
	$this->BestOffer = $value;
	}

	}
/**
 *

 * @return 
 */
	function BestOfferArrayType()
	{
		$this->EbatNs_ComplexType('BestOfferArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'BestOffer' =>
				array(
					'required' => false,
					'type' => 'BestOfferType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
