<?php
// autogenerated file 17.11.2006 13:29
// $Id: BestOfferEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:18 gswkaiser Exp $
// $Log: BestOfferEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:18  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class BestOfferEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function BestOfferEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('BestOfferEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
