<?php
// autogenerated file 17.11.2006 13:29
// $Id: BidderStatusCodeType.php,v 1.1.1.1 2006/12/22 14:37:19 gswkaiser Exp $
// $Log: BidderStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:19  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class BidderStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Approved
	var $Approved = 'Approved';
	// @var string $Denied
	var $Denied = 'Denied';
	// @var string $Pending
	var $Pending = 'Pending';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BidderStatusCodeType()
	{
		$this->EbatNs_FacetType('BidderStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BidderStatusCodeType = new BidderStatusCodeType();

?>
