<?php
// autogenerated file 17.11.2006 13:29
// $Id: BidderIdType.php,v 1.1.1.1 2006/12/22 14:37:19 gswkaiser Exp $
// $Log: BidderIdType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:19  gswkaiser
// no message
//
//
require_once 'EbatNs_SimpleType.php';

class BidderIdType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function BidderIdType()
	{
		$this->EbatNs_SimpleType('BidderIdType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BidderIdType = new BidderIdType();

?>
