<?php
// autogenerated file 17.11.2006 13:29
// $Id: BuyerProtectionCodeType.php,v 1.1.1.1 2006/12/22 14:37:20 gswkaiser Exp $
// $Log: BuyerProtectionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:20  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class BuyerProtectionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ItemIneligible
	var $ItemIneligible = 'ItemIneligible';
	// @var string $ItemEligible
	var $ItemEligible = 'ItemEligible';
	// @var string $ItemMarkedIneligible
	var $ItemMarkedIneligible = 'ItemMarkedIneligible';
	// @var string $ItemMarkedEligible
	var $ItemMarkedEligible = 'ItemMarkedEligible';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BuyerProtectionCodeType()
	{
		$this->EbatNs_FacetType('BuyerProtectionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BuyerProtectionCodeType = new BuyerProtectionCodeType();

?>
