<?php
// autogenerated file 17.11.2006 13:29
// $Id: CalculatedShippingChargeOptionCodeType.php,v 1.1.1.1 2006/12/22 14:37:21 gswkaiser Exp $
// $Log: CalculatedShippingChargeOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:21  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CalculatedShippingChargeOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ChargeEachItem
	var $ChargeEachItem = 'ChargeEachItem';
	// @var string $ChargeEntireOrder
	var $ChargeEntireOrder = 'ChargeEntireOrder';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CalculatedShippingChargeOptionCodeType()
	{
		$this->EbatNs_FacetType('CalculatedShippingChargeOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CalculatedShippingChargeOptionCodeType = new CalculatedShippingChargeOptionCodeType();

?>
