<?php
// autogenerated file 17.11.2006 13:29
// $Id: CategoryListingsOrderCodeType.php,v 1.1.1.1 2006/12/22 14:37:22 gswkaiser Exp $
// $Log: CategoryListingsOrderCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:22  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CategoryListingsOrderCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NoFilter
	var $NoFilter = 'NoFilter';
	// @var string $ItemsBy24Hr
	var $ItemsBy24Hr = 'ItemsBy24Hr';
	// @var string $ItemsEndToday
	var $ItemsEndToday = 'ItemsEndToday';
	// @var string $ItemsEndIn5Hr
	var $ItemsEndIn5Hr = 'ItemsEndIn5Hr';
	// @var string $SortByPriceAsc
	var $SortByPriceAsc = 'SortByPriceAsc';
	// @var string $SortByPriceDesc
	var $SortByPriceDesc = 'SortByPriceDesc';
	// @var string $BestMatchSort
	var $BestMatchSort = 'BestMatchSort';
	// @var string $DistanceSort
	var $DistanceSort = 'DistanceSort';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CategoryListingsOrderCodeType()
	{
		$this->EbatNs_FacetType('CategoryListingsOrderCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CategoryListingsOrderCodeType = new CategoryListingsOrderCodeType();

?>
