<?php
// autogenerated file 17.11.2006 13:29
// $Id: CategoryMappingType.php,v 1.1.1.1 2006/12/22 14:37:22 gswkaiser Exp $
// $Log: CategoryMappingType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:22  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class CategoryMappingType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function CategoryMappingType()
	{
		$this->EbatNs_ComplexType('CategoryMappingType', 'http://www.w3.org/2001/XMLSchema');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'oldID' =>
			array(
				'name' => 'oldID',
				'type' => 'string',
				'use' => 'required'
			),
			'id' =>
			array(
				'name' => 'id',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
