<?php
// autogenerated file 17.11.2006 13:29
// $Id: CategoryArrayType.php,v 1.1.1.1 2006/12/22 14:37:21 gswkaiser Exp $
// $Log: CategoryArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:21  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'CategoryType.php';

class CategoryArrayType extends EbatNs_ComplexType
{
	// start props
	// @var CategoryType $Category
	var $Category;
	// end props

/**
 *

 * @return CategoryType
 * @param  $index 
 */
	function getCategory($index = null)
	{
		if ($index) {
		return $this->Category[$index];
	} else {
		return $this->Category;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setCategory($value, $index = null)
	{
		if ($index) {
	$this->Category[$index] = $value;
	} else {
	$this->Category = $value;
	}

	}
/**
 *

 * @return 
 */
	function CategoryArrayType()
	{
		$this->EbatNs_ComplexType('CategoryArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Category' =>
				array(
					'required' => false,
					'type' => 'CategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
