<?php
// autogenerated file 17.11.2006 13:29
// $Id: CategoryFeatureDetailLevelCodeType.php,v 1.1.1.1 2006/12/22 14:37:21 gswkaiser Exp $
// $Log: CategoryFeatureDetailLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:21  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CategoryFeatureDetailLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ReturnAll
	var $ReturnAll = 'ReturnAll';
	// @var string $ReturnFeatureDefinitions
	var $ReturnFeatureDefinitions = 'ReturnFeatureDefinitions';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CategoryFeatureDetailLevelCodeType()
	{
		$this->EbatNs_FacetType('CategoryFeatureDetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CategoryFeatureDetailLevelCodeType = new CategoryFeatureDetailLevelCodeType();

?>
