<?php
// autogenerated file 17.11.2006 13:29
// $Id: CharityAffiliationsType.php,v 1.1.1.1 2006/12/22 14:37:24 gswkaiser Exp $
// $Log: CharityAffiliationsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:24  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'CharityIDType.php';

class CharityAffiliationsType extends EbatNs_ComplexType
{
	// start props
	// @var CharityIDType $CharityID
	var $CharityID;
	// end props

/**
 *

 * @return CharityIDType
 * @param  $index 
 */
	function getCharityID($index = null)
	{
		if ($index) {
		return $this->CharityID[$index];
	} else {
		return $this->CharityID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setCharityID($value, $index = null)
	{
		if ($index) {
	$this->CharityID[$index] = $value;
	} else {
	$this->CharityID = $value;
	}

	}
/**
 *

 * @return 
 */
	function CharityAffiliationsType()
	{
		$this->EbatNs_ComplexType('CharityAffiliationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CharityID' =>
				array(
					'required' => false,
					'type' => 'CharityIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
