<?php
// autogenerated file 17.11.2006 13:29
// $Id: CharityAffiliationType.php,v 1.1.1.1 2006/12/22 14:37:24 gswkaiser Exp $
// $Log: CharityAffiliationType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:24  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class CharityAffiliationType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function CharityAffiliationType()
	{
		$this->EbatNs_ComplexType('CharityAffiliationType', 'urn:ebay:apis:eBLBaseComponents');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'id' =>
			array(
				'name' => 'id',
				'type' => 'string',
				'use' => 'required'
			),
			'type' =>
			array(
				'name' => 'type',
				'type' => 'CharityAffiliationTypeCodeType',
				'use' => 'required'
			)
		));

	}
}
?>
