<?php
// autogenerated file 17.11.2006 13:29
// $Id: CheckoutStatusCodeType.php,v 1.1.1.1 2006/12/22 14:37:24 gswkaiser Exp $
// $Log: CheckoutStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:24  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CheckoutStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $CheckoutComplete
	var $CheckoutComplete = 'CheckoutComplete';
	// @var string $CheckoutIncomplete
	var $CheckoutIncomplete = 'CheckoutIncomplete';
	// @var string $BuyerRequestsTotal
	var $BuyerRequestsTotal = 'BuyerRequestsTotal';
	// @var string $SellerResponded
	var $SellerResponded = 'SellerResponded';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CheckoutStatusCodeType()
	{
		$this->EbatNs_FacetType('CheckoutStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CheckoutStatusCodeType = new CheckoutStatusCodeType();

?>
