<?php
// autogenerated file 17.11.2006 13:29
// $Id: CombinedPaymentOptionCodeType.php,v 1.1.1.1 2006/12/22 14:37:25 gswkaiser Exp $
// $Log: CombinedPaymentOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:25  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CombinedPaymentOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NoCombinedPayment
	var $NoCombinedPayment = 'NoCombinedPayment';
	// @var string $DiscountSpecified
	var $DiscountSpecified = 'DiscountSpecified';
	// @var string $SpecifyDiscountLater
	var $SpecifyDiscountLater = 'SpecifyDiscountLater';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CombinedPaymentOptionCodeType()
	{
		$this->EbatNs_FacetType('CombinedPaymentOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CombinedPaymentOptionCodeType = new CombinedPaymentOptionCodeType();

?>
