<?php
// autogenerated file 17.11.2006 13:29
// $Id: CommentTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:25 gswkaiser Exp $
// $Log: CommentTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:25  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CommentTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Positive
	var $Positive = 'Positive';
	// @var string $Neutral
	var $Neutral = 'Neutral';
	// @var string $Negative
	var $Negative = 'Negative';
	// @var string $Withdrawn
	var $Withdrawn = 'Withdrawn';
	// @var string $IndependentlyWithdrawn
	var $IndependentlyWithdrawn = 'IndependentlyWithdrawn';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CommentTypeCodeType()
	{
		$this->EbatNs_FacetType('CommentTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CommentTypeCodeType = new CommentTypeCodeType();

?>
