<?php
// autogenerated file 17.11.2006 13:29
// $Id: CompleteSaleResponseType.php,v 1.1.1.1 2006/12/22 14:37:25 gswkaiser Exp $
// $Log: CompleteSaleResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:25  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class CompleteSaleResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function CompleteSaleResponseType()
	{
		$this->AbstractResponseType('CompleteSaleResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
