<?php
// autogenerated file 17.11.2006 13:29
// $Id: CompleteStatusCodeType.php,v 1.1.1.1 2006/12/22 14:37:25 gswkaiser Exp $
// $Log: CompleteStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:25  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class CompleteStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Incomplete
	var $Incomplete = 'Incomplete';
	// @var string $Complete
	var $Complete = 'Complete';
	// @var string $Pending
	var $Pending = 'Pending';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function CompleteStatusCodeType()
	{
		$this->EbatNs_FacetType('CompleteStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CompleteStatusCodeType = new CompleteStatusCodeType();

?>
