<?php
// autogenerated file 17.11.2006 13:29
// $Id: DescriptionReviseModeCodeType.php,v 1.1.1.1 2006/12/22 14:37:27 gswkaiser Exp $
// $Log: DescriptionReviseModeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:27  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DescriptionReviseModeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Replace
	var $Replace = 'Replace';
	// @var string $Prepend
	var $Prepend = 'Prepend';
	// @var string $Append
	var $Append = 'Append';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DescriptionReviseModeCodeType()
	{
		$this->EbatNs_FacetType('DescriptionReviseModeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DescriptionReviseModeCodeType = new DescriptionReviseModeCodeType();

?>
