<?php
// autogenerated file 17.11.2006 13:29
// $Id: DescriptionTemplateType.php,v 1.1.1.1.2.1 2007/04/08 07:16:39 gswkaiser Exp $
// $Log: DescriptionTemplateType.php,v $
// Revision 1.1.1.1.2.1  2007/04/08 07:16:39  gswkaiser
// olcommerce_2_0_0
//
// Update
//
// Revision 1.1.1.1  2006/12/22 14:37:27  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'DescriptionTemplateCodeType.php';

class DescriptionTemplateType extends EbatNs_ComplexType
{
	// start props
	// @var int $GroupID
	var $GroupID;
	// @var int $id
	var $id;
	// @var anyURI $ImageURL
	var $ImageURL;
	// @var string $Name
	var $Name;
	// @var string $TemplateXML
	var $TemplateXML;
	// @var DescriptionTemplateCodeType $Type
	var $Type;
	// end props

/**
 *

 * @return int
 */
	function getGroupID()
	{
		return $this->GroupID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGroupID($value)
	{
		$this->GroupID = $value;
	}
/**
 *

 * @return int
 */
	function getID()
	{
		return $this->id;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setID($value)
	{
		$this->id = $value;
	}
/**
 *

 * @return anyURI
 */
	function getImageURL()
	{
		return $this->ImageURL;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setImageURL($value)
	{
		$this->ImageURL = $value;
	}
/**
 *

 * @return string
 */
	function getName()
	{
		return $this->Name;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setName($value)
	{
		$this->Name = $value;
	}
/**
 *

 * @return string
 */
	function getTemplateXML()
	{
		return $this->TemplateXML;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTemplateXML($value)
	{
		$this->TemplateXML = $value;
	}
/**
 *

 * @return DescriptionTemplateCodeType
 */
	function getType()
	{
		return $this->Type;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setType($value)
	{
		$this->Type = $value;
	}
/**
 *

 * @return 
 */
	function DescriptionTemplateType()
	{
		$this->EbatNs_ComplexType('DescriptionTemplateType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'GroupID' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'id' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ImageURL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Name' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TemplateXML' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Type' =>
				array(
					'required' => false,
					'type' => 'DescriptionTemplateCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
