<?php
// autogenerated file 17.11.2006 13:29
// $Id: DigitalDeliveryMethodCodeType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DigitalDeliveryMethodCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DigitalDeliveryMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $DownloadURL
	var $DownloadURL = 'DownloadURL';
	// @var string $AlternateDeliveryInstructions
	var $AlternateDeliveryInstructions = 'AlternateDeliveryInstructions';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DigitalDeliveryMethodCodeType()
	{
		$this->EbatNs_FacetType('DigitalDeliveryMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DigitalDeliveryMethodCodeType = new DigitalDeliveryMethodCodeType();

?>
