<?php
// autogenerated file 17.11.2006 13:29
// $Id: DigitalDeliveryEnabledCodeType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DigitalDeliveryEnabledCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DigitalDeliveryEnabledCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Disabled
	var $Disabled = 'Disabled';
	// @var string $Enabled
	var $Enabled = 'Enabled';
	// @var string $Promoted
	var $Promoted = 'Promoted';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DigitalDeliveryEnabledCodeType()
	{
		$this->EbatNs_FacetType('DigitalDeliveryEnabledCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DigitalDeliveryEnabledCodeType = new DigitalDeliveryEnabledCodeType();

?>
