<?php
// autogenerated file 17.11.2006 13:29
// $Id: DigitalDeliveryEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DigitalDeliveryEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class DigitalDeliveryEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function DigitalDeliveryEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('DigitalDeliveryEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
