<?php
// autogenerated file 17.11.2006 13:29
// $Id: DisputeRecordTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DisputeRecordTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DisputeRecordTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $UnpaidItem
	var $UnpaidItem = 'UnpaidItem';
	// @var string $ItemNotReceived
	var $ItemNotReceived = 'ItemNotReceived';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DisputeRecordTypeCodeType()
	{
		$this->EbatNs_FacetType('DisputeRecordTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeRecordTypeCodeType = new DisputeRecordTypeCodeType();

?>
