<?php
// autogenerated file 17.11.2006 13:29
// $Id: DisputeReasonCodeType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DisputeReasonCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DisputeReasonCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $BuyerHasNotPaid
	var $BuyerHasNotPaid = 'BuyerHasNotPaid';
	// @var string $TransactionMutuallyCanceled
	var $TransactionMutuallyCanceled = 'TransactionMutuallyCanceled';
	// @var string $ItemNotReceived
	var $ItemNotReceived = 'ItemNotReceived';
	// @var string $SignificantlyNotAsDescribed
	var $SignificantlyNotAsDescribed = 'SignificantlyNotAsDescribed';
	// @var string $NoRefund
	var $NoRefund = 'NoRefund';
	// @var string $ReturnPolicyUnpaidItem
	var $ReturnPolicyUnpaidItem = 'ReturnPolicyUnpaidItem';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DisputeReasonCodeType()
	{
		$this->EbatNs_FacetType('DisputeReasonCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeReasonCodeType = new DisputeReasonCodeType();

?>
