<?php
// autogenerated file 17.11.2006 13:29
// $Id: DisputeFilterTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:28 gswkaiser Exp $
// $Log: DisputeFilterTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class DisputeFilterTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AllInvolvedDisputes
	var $AllInvolvedDisputes = 'AllInvolvedDisputes';
	// @var string $DisputesAwaitingMyResponse
	var $DisputesAwaitingMyResponse = 'DisputesAwaitingMyResponse';
	// @var string $DisputesAwaitingOtherPartyResponse
	var $DisputesAwaitingOtherPartyResponse = 'DisputesAwaitingOtherPartyResponse';
	// @var string $AllInvolvedClosedDisputes
	var $AllInvolvedClosedDisputes = 'AllInvolvedClosedDisputes';
	// @var string $EligibleForCredit
	var $EligibleForCredit = 'EligibleForCredit';
	// @var string $UnpaidItemDisputes
	var $UnpaidItemDisputes = 'UnpaidItemDisputes';
	// @var string $ItemNotReceivedDisputes
	var $ItemNotReceivedDisputes = 'ItemNotReceivedDisputes';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DisputeFilterTypeCodeType()
	{
		$this->EbatNs_FacetType('DisputeFilterTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeFilterTypeCodeType = new DisputeFilterTypeCodeType();

?>
