<?php
// autogenerated file 17.11.2006 13:29
// $Id: DomainHistogramType.php,v 1.1.1.1 2006/12/22 14:37:30 gswkaiser Exp $
// $Log: DomainHistogramType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:30  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ExpressHistogramDepartmentType.php';

class DomainHistogramType extends EbatNs_ComplexType
{
	// start props
	// @var ExpressHistogramDepartmentType $Department
	var $Department;
	// end props

/**
 *

 * @return ExpressHistogramDepartmentType
 * @param  $index 
 */
	function getDepartment($index = null)
	{
		if ($index) {
		return $this->Department[$index];
	} else {
		return $this->Department;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setDepartment($value, $index = null)
	{
		if ($index) {
	$this->Department[$index] = $value;
	} else {
	$this->Department = $value;
	}

	}
/**
 *

 * @return 
 */
	function DomainHistogramType()
	{
		$this->EbatNs_ComplexType('DomainHistogramType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Department' =>
				array(
					'required' => false,
					'type' => 'ExpressHistogramDepartmentType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
