<?php
// autogenerated file 17.11.2006 13:29
// $Id: DutchBINEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:30 gswkaiser Exp $
// $Log: DutchBINEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:30  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class DutchBINEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function DutchBINEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('DutchBINEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
