<?php
// autogenerated file 03.02.2006 11:21
// $Id: EbatNsCsSetExt_CurrentTimeType.php,v 1.1.1.1 2006/12/22 14:37:32 gswkaiser Exp $
// $Log: EbatNsCsSetExt_CurrentTimeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:32  gswkaiser
// no message
//
// Revision 1.1  2006/02/03 10:52:01  michael
// initial checkin
//
//
require_once 'EbatNs_ComplexType.php';

class EbatNsCsSetExt_CurrentTimeType extends EbatNs_ComplexType
{
	// start props
	// @var string $DateMedium
	var $DateMedium;
	// @var string $TimeLong
	var $TimeLong;
	// end props

/**
 *

 * @return string
 */
	function getDateMedium()
	{
		return $this->DateMedium;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDateMedium($value)
	{
		$this->DateMedium = $value;
	}
/**
 *

 * @return string
 */
	function getTimeLong()
	{
		return $this->TimeLong;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTimeLong($value)
	{
		$this->TimeLong = $value;
	}
/**
 *

 * @return 
 */
	function EbatNsCsSetExt_CurrentTimeType()
	{
		$this->EbatNs_ComplexType('EbatNsCsSetExt_CurrentTimeType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
		$this->_elements = array_merge($this->_elements,
			array(
				'DateMedium' =>
				array(
					'required' => true,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				),
				'TimeLong' =>
				array(
					'required' => true,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				)
			));

	}
}
?>
