<?php
// autogenerated file 03.02.2006 11:21
// $Id: EbatNsCsSetExt_CharacteristicsListType.php,v 1.1.1.1 2006/12/22 14:37:31 gswkaiser Exp $
// $Log: EbatNsCsSetExt_CharacteristicsListType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:31  gswkaiser
// no message
//
// Revision 1.1  2006/02/03 10:52:01  michael
// initial checkin
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'EbatNsCsSetExt_AttributeArrayType.php';

class EbatNsCsSetExt_CharacteristicsListType extends EbatNs_ComplexType
{
	// start props
	// @var EbatNsCsSetExt_AttributeArrayType $Initial
	var $Initial;
	// @var EbatNsCsSetExt_AttributeArrayType $Conditional
	var $Conditional;
	// @var EbatNsCsSetExt_AttributeArrayType $Other
	var $Other;
	// end props

/**
 *

 * @return EbatNsCsSetExt_AttributeArrayType
 */
	function getInitial()
	{
		return $this->Initial;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setInitial($value)
	{
		$this->Initial = $value;
	}
/**
 *

 * @return EbatNsCsSetExt_AttributeArrayType
 */
	function getConditional()
	{
		return $this->Conditional;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setConditional($value)
	{
		$this->Conditional = $value;
	}
/**
 *

 * @return EbatNsCsSetExt_AttributeArrayType
 */
	function getOther()
	{
		return $this->Other;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOther($value)
	{
		$this->Other = $value;
	}
/**
 *

 * @return 
 */
	function EbatNsCsSetExt_CharacteristicsListType()
	{
		$this->EbatNs_ComplexType('EbatNsCsSetExt_CharacteristicsListType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
		$this->_elements = array_merge($this->_elements,
			array(
				'Initial' =>
				array(
					'required' => true,
					'type' => 'EbatNsCsSetExt_AttributeArrayType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => false,
					'cardinality' => '1..1'
				),
				'Conditional' =>
				array(
					'required' => true,
					'type' => 'EbatNsCsSetExt_AttributeArrayType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => false,
					'cardinality' => '1..1'
				),
				'Other' =>
				array(
					'required' => true,
					'type' => 'EbatNsCsSetExt_AttributeArrayType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => false,
					'cardinality' => '1..1'
				)
			));

	}
}
?>
