<?php
// autogenerated file 17.11.2006 13:30
// $Id: eBxOptInPreferenceType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: eBxOptInPreferenceType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class eBxOptInPreferenceType extends EbatNs_ComplexType
{
	// start props
	// @var boolean $eBxOptInPreference
	var $eBxOptInPreference;
	// end props

/**
 *

 * @return boolean
 */
	function geteBxOptInPreference()
	{
		return $this->eBxOptInPreference;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function seteBxOptInPreference($value)
	{
		$this->eBxOptInPreference = $value;
	}
/**
 *

 * @return 
 */
	function eBxOptInPreferenceType()
	{
		$this->EbatNs_ComplexType('eBxOptInPreferenceType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'eBxOptInPreference' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
