<?php
// autogenerated file 17.11.2006 13:29
// $Id: EnableCodeType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: EnableCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class EnableCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Enable
	var $Enable = 'Enable';
	// @var string $Disable
	var $Disable = 'Disable';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function EnableCodeType()
	{
		$this->EbatNs_FacetType('EnableCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_EnableCodeType = new EnableCodeType();

?>
