<?php
// autogenerated file 17.11.2006 13:29
// $Id: EndItemRequestType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: EndItemRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EndReasonCodeType.php';
require_once 'AbstractRequestType.php';
require_once 'ItemIDType.php';

class EndItemRequestType extends AbstractRequestType
{
	// start props
	// @var ItemIDType $ItemID
	var $ItemID;
	// @var EndReasonCodeType $EndingReason
	var $EndingReason;
	// @var string $SellerInventoryID
	var $SellerInventoryID;
	// end props

/**
 *

 * @return ItemIDType
 */
	function getItemID()
	{
		return $this->ItemID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
/**
 *

 * @return EndReasonCodeType
 */
	function getEndingReason()
	{
		return $this->EndingReason;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEndingReason($value)
	{
		$this->EndingReason = $value;
	}
/**
 *

 * @return string
 */
	function getSellerInventoryID()
	{
		return $this->SellerInventoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellerInventoryID($value)
	{
		$this->SellerInventoryID = $value;
	}
/**
 *

 * @return 
 */
	function EndItemRequestType()
	{
		$this->AbstractRequestType('EndItemRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemID' =>
				array(
					'required' => false,
					'type' => 'ItemIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EndingReason' =>
				array(
					'required' => false,
					'type' => 'EndReasonCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellerInventoryID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
