<?php
// autogenerated file 17.11.2006 13:29
// $Id: EndOfAuctionLogoTypeCodeType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: EndOfAuctionLogoTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class EndOfAuctionLogoTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $WinningBidderNotice
	var $WinningBidderNotice = 'WinningBidderNotice';
	// @var string $Store
	var $Store = 'Store';
	// @var string $Customized
	var $Customized = 'Customized';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $None
	var $None = 'None';
	// end props

/**
 *

 * @return 
 */
	function EndOfAuctionLogoTypeCodeType()
	{
		$this->EbatNs_FacetType('EndOfAuctionLogoTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_EndOfAuctionLogoTypeCodeType = new EndOfAuctionLogoTypeCodeType();

?>
