<?php
// autogenerated file 17.11.2006 13:29
// $Id: ErrorParameterType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: ErrorParameterType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ErrorParameterType extends EbatNs_ComplexType
{
	// start props
	// @var string $Value
	var $Value;
	// end props

/**
 *

 * @return string
 */
	function getValue()
	{
		return $this->Value;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setValue($value)
	{
		$this->Value = $value;
	}
/**
 *

 * @return 
 */
	function ErrorParameterType()
	{
		$this->EbatNs_ComplexType('ErrorParameterType', 'http://www.w3.org/2001/XMLSchema');
		$this->_elements = array_merge($this->_elements,
			array(
				'Value' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));
	$this->_attributes = array_merge($this->_attributes,
		array(
			'ParamID' =>
			array(
				'name' => 'ParamID',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
