<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressDetailLevelCodeType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: ExpressDetailLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ExpressDetailLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Coarse
	var $Coarse = 'Coarse';
	// @var string $Fine
	var $Fine = 'Fine';
	// @var string $None
	var $None = 'None';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ExpressDetailLevelCodeType()
	{
		$this->EbatNs_FacetType('ExpressDetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressDetailLevelCodeType = new ExpressDetailLevelCodeType();

?>
