<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressSellingPreferenceCodeType.php,v 1.1.1.1 2006/12/22 14:37:46 gswkaiser Exp $
// $Log: ExpressSellingPreferenceCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:46  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ExpressSellingPreferenceCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $All
	var $All = 'All';
	// @var string $ExpressOnly
	var $ExpressOnly = 'ExpressOnly';
	// @var string $OptOut
	var $OptOut = 'OptOut';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ExpressSellingPreferenceCodeType()
	{
		$this->EbatNs_FacetType('ExpressSellingPreferenceCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressSellingPreferenceCodeType = new ExpressSellingPreferenceCodeType();

?>
