<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressProductSortCodeType.php,v 1.1.1.1 2006/12/22 14:37:46 gswkaiser Exp $
// $Log: ExpressProductSortCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:46  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ExpressProductSortCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $LowestPrice
	var $LowestPrice = 'LowestPrice';
	// @var string $HighestPrice
	var $HighestPrice = 'HighestPrice';
	// @var string $SalesRank
	var $SalesRank = 'SalesRank';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ExpressProductSortCodeType()
	{
		$this->EbatNs_FacetType('ExpressProductSortCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressProductSortCodeType = new ExpressProductSortCodeType();

?>
