<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressConditionRequiredDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:44 gswkaiser Exp $
// $Log: ExpressConditionRequiredDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:44  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ExpressConditionRequiredDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function ExpressConditionRequiredDefinitionType()
	{
		$this->EbatNs_ComplexType('ExpressConditionRequiredDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
