<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressItemSortCodeType.php,v 1.1.1.1 2006/12/22 14:37:46 gswkaiser Exp $
// $Log: ExpressItemSortCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:46  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ExpressItemSortCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $LowestTotalCost
	var $LowestTotalCost = 'LowestTotalCost';
	// @var string $HighestTotalCost
	var $HighestTotalCost = 'HighestTotalCost';
	// @var string $Relevance
	var $Relevance = 'Relevance';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ExpressItemSortCodeType()
	{
		$this->EbatNs_FacetType('ExpressItemSortCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressItemSortCodeType = new ExpressItemSortCodeType();

?>
