<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressHistogramProductType.php,v 1.1.1.1 2006/12/22 14:37:45 gswkaiser Exp $
// $Log: ExpressHistogramProductType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:45  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ExpressHistogramDomainDetailsType.php';

class ExpressHistogramProductType extends EbatNs_ComplexType
{
	// start props
	// @var ExpressHistogramDomainDetailsType $DomainDetails
	var $DomainDetails;
	// end props

/**
 *

 * @return ExpressHistogramDomainDetailsType
 */
	function getDomainDetails()
	{
		return $this->DomainDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDomainDetails($value)
	{
		$this->DomainDetails = $value;
	}
/**
 *

 * @return 
 */
	function ExpressHistogramProductType()
	{
		$this->EbatNs_ComplexType('ExpressHistogramProductType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'DomainDetails' =>
				array(
					'required' => false,
					'type' => 'ExpressHistogramDomainDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
