<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExpressEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:37:45 gswkaiser Exp $
// $Log: ExpressEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:45  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ExpressEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function ExpressEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('ExpressEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
