<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExternalProductIDType.php,v 1.1.1.1 2006/12/22 14:37:47 gswkaiser Exp $
// $Log: ExternalProductIDType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:47  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ExternalProductCodeType.php';

class ExternalProductIDType extends EbatNs_ComplexType
{
	// start props
	// @var string $Value
	var $Value;
	// @var boolean $ReturnSearchResultOnDuplicates
	var $ReturnSearchResultOnDuplicates;
	// @var ExternalProductCodeType $Type
	var $Type;
	// end props

/**
 *

 * @return string
 */
	function getValue()
	{
		return $this->Value;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setValue($value)
	{
		$this->Value = $value;
	}
/**
 *

 * @return boolean
 */
	function getReturnSearchResultOnDuplicates()
	{
		return $this->ReturnSearchResultOnDuplicates;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReturnSearchResultOnDuplicates($value)
	{
		$this->ReturnSearchResultOnDuplicates = $value;
	}
/**
 *

 * @return ExternalProductCodeType
 */
	function getType()
	{
		return $this->Type;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setType($value)
	{
		$this->Type = $value;
	}
/**
 *

 * @return 
 */
	function ExternalProductIDType()
	{
		$this->EbatNs_ComplexType('ExternalProductIDType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Value' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReturnSearchResultOnDuplicates' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Type' =>
				array(
					'required' => false,
					'type' => 'ExternalProductCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
