<?php
// autogenerated file 17.11.2006 13:29
// $Id: ExternalAlertIDArrayType.php,v 1.1.1.1 2006/12/22 14:37:46 gswkaiser Exp $
// $Log: ExternalAlertIDArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:46  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ExternalAlertIDArrayType extends EbatNs_ComplexType
{
	// start props
	// @var string $ExternalAlertID
	var $ExternalAlertID;
	// end props

/**
 *

 * @return string
 * @param  $index 
 */
	function getExternalAlertID($index = null)
	{
		if ($index) {
		return $this->ExternalAlertID[$index];
	} else {
		return $this->ExternalAlertID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setExternalAlertID($value, $index = null)
	{
		if ($index) {
	$this->ExternalAlertID[$index] = $value;
	} else {
	$this->ExternalAlertID = $value;
	}

	}
/**
 *

 * @return 
 */
	function ExternalAlertIDArrayType()
	{
		$this->EbatNs_ComplexType('ExternalAlertIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ExternalAlertID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
