<?php
// autogenerated file 17.11.2006 13:29
// $Id: FaultDetailsType.php,v 1.1.1.1 2006/12/22 14:37:47 gswkaiser Exp $
// $Log: FaultDetailsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:47  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class FaultDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var string $ErrorCode
	var $ErrorCode;
	// @var string $Severity
	var $Severity;
	// @var string $DetailedMessage
	var $DetailedMessage;
	// end props

/**
 *

 * @return string
 */
	function getErrorCode()
	{
		return $this->ErrorCode;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setErrorCode($value)
	{
		$this->ErrorCode = $value;
	}
/**
 *

 * @return string
 */
	function getSeverity()
	{
		return $this->Severity;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSeverity($value)
	{
		$this->Severity = $value;
	}
/**
 *

 * @return string
 */
	function getDetailedMessage()
	{
		return $this->DetailedMessage;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDetailedMessage($value)
	{
		$this->DetailedMessage = $value;
	}
/**
 *

 * @return 
 */
	function FaultDetailsType()
	{
		$this->EbatNs_ComplexType('FaultDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ErrorCode' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Severity' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DetailedMessage' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
