<?php
// autogenerated file 17.11.2006 13:29
// $Id: FeatureIDCodeType.php,v 1.1.1.1 2006/12/22 14:37:48 gswkaiser Exp $
// $Log: FeatureIDCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:48  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class FeatureIDCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ListingDurations
	var $ListingDurations = 'ListingDurations';
	// @var string $BestOfferEnabled
	var $BestOfferEnabled = 'BestOfferEnabled';
	// @var string $DutchBINEnabled
	var $DutchBINEnabled = 'DutchBINEnabled';
	// @var string $ShippingTermsRequired
	var $ShippingTermsRequired = 'ShippingTermsRequired';
	// @var string $UserConsentRequired
	var $UserConsentRequired = 'UserConsentRequired';
	// @var string $HomePageFeaturedEnabled
	var $HomePageFeaturedEnabled = 'HomePageFeaturedEnabled';
	// @var string $AdFormatEnabled
	var $AdFormatEnabled = 'AdFormatEnabled';
	// @var string $DigitalDeliveryEnabled
	var $DigitalDeliveryEnabled = 'DigitalDeliveryEnabled';
	// @var string $BestOfferCounterEnabled
	var $BestOfferCounterEnabled = 'BestOfferCounterEnabled';
	// @var string $BestOfferAutoDeclineEnabled
	var $BestOfferAutoDeclineEnabled = 'BestOfferAutoDeclineEnabled';
	// @var string $ProPack
	var $ProPack = 'ProPack';
	// @var string $BasicUpgradePack
	var $BasicUpgradePack = 'BasicUpgradePack';
	// @var string $ValuePack
	var $ValuePack = 'ValuePack';
	// @var string $ProPackPlus
	var $ProPackPlus = 'ProPackPlus';
	// @var string $LocalMarketSpecialitySubscription
	var $LocalMarketSpecialitySubscription = 'LocalMarketSpecialitySubscription';
	// @var string $LocalMarketRegularSubscription
	var $LocalMarketRegularSubscription = 'LocalMarketRegularSubscription';
	// @var string $LocalMarketPremiumSubscription
	var $LocalMarketPremiumSubscription = 'LocalMarketPremiumSubscription';
	// @var string $LocalMarketNonSubscription
	var $LocalMarketNonSubscription = 'LocalMarketNonSubscription';
	// @var string $ExpressEnabled
	var $ExpressEnabled = 'ExpressEnabled';
	// @var string $ExpressPicturesRequired
	var $ExpressPicturesRequired = 'ExpressPicturesRequired';
	// @var string $ExpressConditionRequired
	var $ExpressConditionRequired = 'ExpressConditionRequired';
	// @var string $SellerContactDetailsEnabled
	var $SellerContactDetailsEnabled = 'SellerContactDetailsEnabled';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $MinimumReservePrice
	var $MinimumReservePrice = 'MinimumReservePrice';
	// @var string $TransactionConfirmationRequestEnabled
	var $TransactionConfirmationRequestEnabled = 'TransactionConfirmationRequestEnabled';
	// @var string $StoreInventoryEnabled
	var $StoreInventoryEnabled = 'StoreInventoryEnabled';
	// @var string $LocalListingDistances
	var $LocalListingDistances = 'LocalListingDistances';
	// @var string $SkypeMeTransactionalEnabled
	var $SkypeMeTransactionalEnabled = 'SkypeMeTransactionalEnabled';
	// @var string $SkypeMeNonTransactionalEnabled
	var $SkypeMeNonTransactionalEnabled = 'SkypeMeNonTransactionalEnabled';
	// end props

/**
 *

 * @return 
 */
	function FeatureIDCodeType()
	{
		$this->EbatNs_FacetType('FeatureIDCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FeatureIDCodeType = new FeatureIDCodeType();

?>
