<?php
// autogenerated file 17.11.2006 13:29
// $Id: FeedbackRequirementsType.php,v 1.1.1.1 2006/12/22 14:37:49 gswkaiser Exp $
// $Log: FeedbackRequirementsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:49  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class FeedbackRequirementsType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function FeedbackRequirementsType()
	{
		$this->EbatNs_ComplexType('FeedbackRequirementsType', 'http://www.w3.org/2001/XMLSchema');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'minimum' =>
			array(
				'name' => 'minimum',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
