<?php
// autogenerated file 17.11.2006 13:29
// $Id: FeedbackResponseCodeType.php,v 1.1.1.1 2006/12/22 14:37:49 gswkaiser Exp $
// $Log: FeedbackResponseCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:49  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class FeedbackResponseCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Reply
	var $Reply = 'Reply';
	// @var string $FollowUp
	var $FollowUp = 'FollowUp';
	// end props

/**
 *

 * @return 
 */
	function FeedbackResponseCodeType()
	{
		$this->EbatNs_FacetType('FeedbackResponseCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FeedbackResponseCodeType = new FeedbackResponseCodeType();

?>
