<?php
// autogenerated file 17.11.2006 13:29
// $Id: FetchTokenResponseType.php,v 1.1.1.1 2006/12/22 14:37:50 gswkaiser Exp $
// $Log: FetchTokenResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:50  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class FetchTokenResponseType extends AbstractResponseType
{
	// start props
	// @var string $eBayAuthToken
	var $eBayAuthToken;
	// @var dateTime $HardExpirationTime
	var $HardExpirationTime;
	// end props

/**
 *

 * @return string
 */
	function geteBayAuthToken()
	{
		return $this->eBayAuthToken;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function seteBayAuthToken($value)
	{
		$this->eBayAuthToken = $value;
	}
/**
 *

 * @return dateTime
 */
	function getHardExpirationTime()
	{
		return $this->HardExpirationTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHardExpirationTime($value)
	{
		$this->HardExpirationTime = $value;
	}
/**
 *

 * @return 
 */
	function FetchTokenResponseType()
	{
		$this->AbstractResponseType('FetchTokenResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'eBayAuthToken' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'HardExpirationTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
