<?php
// autogenerated file 17.11.2006 13:29
// $Id: FetchTokenRequestType.php,v 1.1.1.1 2006/12/22 14:37:49 gswkaiser Exp $
// $Log: FetchTokenRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:49  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class FetchTokenRequestType extends AbstractRequestType
{
	// start props
	// @var string $SecretID
	var $SecretID;
	// end props

/**
 *

 * @return string
 */
	function getSecretID()
	{
		return $this->SecretID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSecretID($value)
	{
		$this->SecretID = $value;
	}
/**
 *

 * @return 
 */
	function FetchTokenRequestType()
	{
		$this->AbstractRequestType('FetchTokenRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SecretID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
