<?php
// autogenerated file 17.11.2006 13:29
// $Id: FlatShippingRateOptionCodeType.php,v 1.1.1.1 2006/12/22 14:37:50 gswkaiser Exp $
// $Log: FlatShippingRateOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:50  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class FlatShippingRateOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ChargeAmountForEachAdditionalItem
	var $ChargeAmountForEachAdditionalItem = 'ChargeAmountForEachAdditionalItem';
	// @var string $DeductAmountFromEachAdditionalItem
	var $DeductAmountFromEachAdditionalItem = 'DeductAmountFromEachAdditionalItem';
	// @var string $ShipAdditionalItemsFree
	var $ShipAdditionalItemsFree = 'ShipAdditionalItemsFree';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function FlatShippingRateOptionCodeType()
	{
		$this->EbatNs_FacetType('FlatShippingRateOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FlatShippingRateOptionCodeType = new FlatShippingRateOptionCodeType();

?>
