<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetAttributesXSLResponseType.php,v 1.1.1.1 2006/12/22 14:37:52 gswkaiser Exp $
// $Log: GetAttributesXSLResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:52  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';
require_once 'XSLFileType.php';

class GetAttributesXSLResponseType extends AbstractResponseType
{
	// start props
	// @var XSLFileType $XSLFile
	var $XSLFile;
	// end props

/**
 *

 * @return XSLFileType
 * @param  $index 
 */
	function getXSLFile($index = null)
	{
		if ($index) {
		return $this->XSLFile[$index];
	} else {
		return $this->XSLFile;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setXSLFile($value, $index = null)
	{
		if ($index) {
	$this->XSLFile[$index] = $value;
	} else {
	$this->XSLFile = $value;
	}

	}
/**
 *

 * @return 
 */
	function GetAttributesXSLResponseType()
	{
		$this->AbstractResponseType('GetAttributesXSLResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'XSLFile' =>
				array(
					'required' => false,
					'type' => 'XSLFileType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
