<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetAllBiddersModeCodeType.php,v 1.1.1.1 2006/12/22 14:37:51 gswkaiser Exp $
// $Log: GetAllBiddersModeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:51  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class GetAllBiddersModeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ViewAll
	var $ViewAll = 'ViewAll';
	// @var string $EndedListing
	var $EndedListing = 'EndedListing';
	// @var string $SecondChanceEligibleEndedListing
	var $SecondChanceEligibleEndedListing = 'SecondChanceEligibleEndedListing';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function GetAllBiddersModeCodeType()
	{
		$this->EbatNs_FacetType('GetAllBiddersModeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_GetAllBiddersModeCodeType = new GetAllBiddersModeCodeType();

?>
