<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetApiAccessRulesRequestType.php,v 1.1.1.1 2006/12/22 14:37:51 gswkaiser Exp $
// $Log: GetApiAccessRulesRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:51  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class GetApiAccessRulesRequestType extends AbstractRequestType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function GetApiAccessRulesRequestType()
	{
		$this->AbstractRequestType('GetApiAccessRulesRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
