<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetBestOffersResponseType.php,v 1.1.1.1 2006/12/22 14:37:52 gswkaiser Exp $
// $Log: GetBestOffersResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:52  gswkaiser
// no message
//
//
require_once 'BestOfferArrayType.php';
require_once 'AbstractResponseType.php';
require_once 'ItemType.php';

class GetBestOffersResponseType extends AbstractResponseType
{
	// start props
	// @var BestOfferArrayType $BestOfferArray
	var $BestOfferArray;
	// @var ItemType $Item
	var $Item;
	// end props

/**
 *

 * @return BestOfferArrayType
 */
	function getBestOfferArray()
	{
		return $this->BestOfferArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferArray($value)
	{
		$this->BestOfferArray = $value;
	}
/**
 *

 * @return ItemType
 */
	function getItem()
	{
		return $this->Item;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItem($value)
	{
		$this->Item = $value;
	}
/**
 *

 * @return 
 */
	function GetBestOffersResponseType()
	{
		$this->AbstractResponseType('GetBestOffersResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'BestOfferArray' =>
				array(
					'required' => false,
					'type' => 'BestOfferArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Item' =>
				array(
					'required' => false,
					'type' => 'ItemType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
