<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetCategory2FinanceOfferResponseType.php,v 1.1.1.1 2006/12/22 14:37:53 gswkaiser Exp $
// $Log: GetCategory2FinanceOfferResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:53  gswkaiser
// no message
//
//
require_once 'CategoryFinanceOfferArrayType.php';
require_once 'AbstractResponseType.php';

class GetCategory2FinanceOfferResponseType extends AbstractResponseType
{
	// start props
	// @var int $Count
	var $Count;
	// @var CategoryFinanceOfferArrayType $CategoryFinanceOfferArray
	var $CategoryFinanceOfferArray;
	// end props

/**
 *

 * @return int
 */
	function getCount()
	{
		return $this->Count;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCount($value)
	{
		$this->Count = $value;
	}
/**
 *

 * @return CategoryFinanceOfferArrayType
 */
	function getCategoryFinanceOfferArray()
	{
		return $this->CategoryFinanceOfferArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryFinanceOfferArray($value)
	{
		$this->CategoryFinanceOfferArray = $value;
	}
/**
 *

 * @return 
 */
	function GetCategory2FinanceOfferResponseType()
	{
		$this->AbstractResponseType('GetCategory2FinanceOfferResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Count' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CategoryFinanceOfferArray' =>
				array(
					'required' => false,
					'type' => 'CategoryFinanceOfferArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
