<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetCrossPromotionsResponseType.php,v 1.1.1.1 2006/12/22 14:37:55 gswkaiser Exp $
// $Log: GetCrossPromotionsResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:55  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';
require_once 'CrossPromotionsType.php';

class GetCrossPromotionsResponseType extends AbstractResponseType
{
	// start props
	// @var CrossPromotionsType $CrossPromotion
	var $CrossPromotion;
	// end props

/**
 *

 * @return CrossPromotionsType
 */
	function getCrossPromotion()
	{
		return $this->CrossPromotion;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCrossPromotion($value)
	{
		$this->CrossPromotion = $value;
	}
/**
 *

 * @return 
 */
	function GetCrossPromotionsResponseType()
	{
		$this->AbstractResponseType('GetCrossPromotionsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CrossPromotion' =>
				array(
					'required' => false,
					'type' => 'CrossPromotionsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
