<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetCategory2FinanceOfferRequestType.php,v 1.1.1.1 2006/12/22 14:37:53 gswkaiser Exp $
// $Log: GetCategory2FinanceOfferRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:53  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class GetCategory2FinanceOfferRequestType extends AbstractRequestType
{
	// start props
	// @var string $CategoryID
	var $CategoryID;
	// @var dateTime $LastModifiedDate
	var $LastModifiedDate;
	// end props

/**
 *

 * @return string
 */
	function getCategoryID()
	{
		return $this->CategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryID($value)
	{
		$this->CategoryID = $value;
	}
/**
 *

 * @return dateTime
 */
	function getLastModifiedDate()
	{
		return $this->LastModifiedDate;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLastModifiedDate($value)
	{
		$this->LastModifiedDate = $value;
	}
/**
 *

 * @return 
 */
	function GetCategory2FinanceOfferRequestType()
	{
		$this->AbstractRequestType('GetCategory2FinanceOfferRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CategoryID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LastModifiedDate' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
