<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetDisputeRequestType.php,v 1.1.1.1 2006/12/22 14:37:56 gswkaiser Exp $
// $Log: GetDisputeRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:56  gswkaiser
// no message
//
//
require_once 'DisputeIDType.php';
require_once 'AbstractRequestType.php';

class GetDisputeRequestType extends AbstractRequestType
{
	// start props
	// @var DisputeIDType $DisputeID
	var $DisputeID;
	// end props

/**
 *

 * @return DisputeIDType
 */
	function getDisputeID()
	{
		return $this->DisputeID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDisputeID($value)
	{
		$this->DisputeID = $value;
	}
/**
 *

 * @return 
 */
	function GetDisputeRequestType()
	{
		$this->AbstractRequestType('GetDisputeRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'DisputeID' =>
				array(
					'required' => false,
					'type' => 'DisputeIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
