<?php
// autogenerated file 17.11.2006 13:29
// $Id: GeteBayOfficialTimeResponseType.php,v 1.1.1.1 2006/12/22 14:37:56 gswkaiser Exp $
// $Log: GeteBayOfficialTimeResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:56  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class GeteBayOfficialTimeResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function GeteBayOfficialTimeResponseType()
	{
		$this->AbstractResponseType('GeteBayOfficialTimeResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
