<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetFinanceOffersRequestType.php,v 1.1.1.1 2006/12/22 14:37:56 gswkaiser Exp $
// $Log: GetFinanceOffersRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:56  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class GetFinanceOffersRequestType extends AbstractRequestType
{
	// start props
	// @var string $FinanceOfferID
	var $FinanceOfferID;
	// @var dateTime $LastModifiedDate
	var $LastModifiedDate;
	// end props

/**
 *

 * @return string
 */
	function getFinanceOfferID()
	{
		return $this->FinanceOfferID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFinanceOfferID($value)
	{
		$this->FinanceOfferID = $value;
	}
/**
 *

 * @return dateTime
 */
	function getLastModifiedDate()
	{
		return $this->LastModifiedDate;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLastModifiedDate($value)
	{
		$this->LastModifiedDate = $value;
	}
/**
 *

 * @return 
 */
	function GetFinanceOffersRequestType()
	{
		$this->AbstractRequestType('GetFinanceOffersRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FinanceOfferID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LastModifiedDate' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
