<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetItemRecommendationsResponseType.php,v 1.1.1.1 2006/12/22 14:37:57 gswkaiser Exp $
// $Log: GetItemRecommendationsResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:57  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';
require_once 'GetRecommendationsResponseContainerType.php';

class GetItemRecommendationsResponseType extends AbstractResponseType
{
	// start props
	// @var GetRecommendationsResponseContainerType $GetRecommendationsResponseContainer
	var $GetRecommendationsResponseContainer;
	// end props

/**
 *

 * @return GetRecommendationsResponseContainerType
 * @param  $index 
 */
	function getGetRecommendationsResponseContainer($index = null)
	{
		if ($index) {
		return $this->GetRecommendationsResponseContainer[$index];
	} else {
		return $this->GetRecommendationsResponseContainer;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setGetRecommendationsResponseContainer($value, $index = null)
	{
		if ($index) {
	$this->GetRecommendationsResponseContainer[$index] = $value;
	} else {
	$this->GetRecommendationsResponseContainer = $value;
	}

	}
/**
 *

 * @return 
 */
	function GetItemRecommendationsResponseType()
	{
		$this->AbstractResponseType('GetItemRecommendationsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'GetRecommendationsResponseContainer' =>
				array(
					'required' => false,
					'type' => 'GetRecommendationsResponseContainerType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
