<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetItemsAwaitingFeedbackResponseType.php,v 1.1.1.1 2006/12/22 14:37:57 gswkaiser Exp $
// $Log: GetItemsAwaitingFeedbackResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:57  gswkaiser
// no message
//
//
require_once 'PaginatedTransactionArrayType.php';
require_once 'AbstractResponseType.php';

class GetItemsAwaitingFeedbackResponseType extends AbstractResponseType
{
	// start props
	// @var PaginatedTransactionArrayType $ItemsAwaitingFeedback
	var $ItemsAwaitingFeedback;
	// end props

/**
 *

 * @return PaginatedTransactionArrayType
 */
	function getItemsAwaitingFeedback()
	{
		return $this->ItemsAwaitingFeedback;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemsAwaitingFeedback($value)
	{
		$this->ItemsAwaitingFeedback = $value;
	}
/**
 *

 * @return 
 */
	function GetItemsAwaitingFeedbackResponseType()
	{
		$this->AbstractResponseType('GetItemsAwaitingFeedbackResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemsAwaitingFeedback' =>
				array(
					'required' => false,
					'type' => 'PaginatedTransactionArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
