<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetItemRequestType.php,v 1.1.1.1 2006/12/22 14:37:57 gswkaiser Exp $
// $Log: GetItemRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:37:57  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';
require_once 'ItemIDType.php';

class GetItemRequestType extends AbstractRequestType
{
	// start props
	// @var ItemIDType $ItemID
	var $ItemID;
	// @var boolean $IncludeExpressRequirements
	var $IncludeExpressRequirements;
	// @var boolean $IncludeWatchCount
	var $IncludeWatchCount;
	// @var boolean $IncludeCrossPromotion
	var $IncludeCrossPromotion;
	// end props

/**
 *

 * @return ItemIDType
 */
	function getItemID()
	{
		return $this->ItemID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
/**
 *

 * @return boolean
 */
	function getIncludeExpressRequirements()
	{
		return $this->IncludeExpressRequirements;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setIncludeExpressRequirements($value)
	{
		$this->IncludeExpressRequirements = $value;
	}
/**
 *

 * @return boolean
 */
	function getIncludeWatchCount()
	{
		return $this->IncludeWatchCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setIncludeWatchCount($value)
	{
		$this->IncludeWatchCount = $value;
	}
/**
 *

 * @return boolean
 */
	function getIncludeCrossPromotion()
	{
		return $this->IncludeCrossPromotion;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setIncludeCrossPromotion($value)
	{
		$this->IncludeCrossPromotion = $value;
	}
/**
 *

 * @return 
 */
	function GetItemRequestType()
	{
		$this->AbstractRequestType('GetItemRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemID' =>
				array(
					'required' => false,
					'type' => 'ItemIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeExpressRequirements' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeWatchCount' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeCrossPromotion' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
