<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetMyMessagesResponseType.php,v 1.1.1.1 2006/12/22 14:38:00 gswkaiser Exp $
// $Log: GetMyMessagesResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:00  gswkaiser
// no message
//
//
require_once 'MyMessagesSummaryType.php';
require_once 'MyMessagesAlertArrayType.php';
require_once 'AbstractResponseType.php';
require_once 'MyMessagesMessageArrayType.php';

class GetMyMessagesResponseType extends AbstractResponseType
{
	// start props
	// @var MyMessagesSummaryType $Summary
	var $Summary;
	// @var MyMessagesAlertArrayType $Alerts
	var $Alerts;
	// @var MyMessagesMessageArrayType $Messages
	var $Messages;
	// end props

/**
 *

 * @return MyMessagesSummaryType
 */
	function getSummary()
	{
		return $this->Summary;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSummary($value)
	{
		$this->Summary = $value;
	}
/**
 *

 * @return MyMessagesAlertArrayType
 */
	function getAlerts()
	{
		return $this->Alerts;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAlerts($value)
	{
		$this->Alerts = $value;
	}
/**
 *

 * @return MyMessagesMessageArrayType
 */
	function getMessages()
	{
		return $this->Messages;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMessages($value)
	{
		$this->Messages = $value;
	}
/**
 *

 * @return 
 */
	function GetMyMessagesResponseType()
	{
		$this->AbstractResponseType('GetMyMessagesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Summary' =>
				array(
					'required' => false,
					'type' => 'MyMessagesSummaryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Alerts' =>
				array(
					'required' => false,
					'type' => 'MyMessagesAlertArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Messages' =>
				array(
					'required' => false,
					'type' => 'MyMessagesMessageArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
