<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetOrderTransactionsRequestType.php,v 1.1.1.1 2006/12/22 14:38:01 gswkaiser Exp $
// $Log: GetOrderTransactionsRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:01  gswkaiser
// no message
//
//
require_once 'ItemTransactionIDArrayType.php';
require_once 'OrderIDArrayType.php';
require_once 'AbstractRequestType.php';

class GetOrderTransactionsRequestType extends AbstractRequestType
{
	// start props
	// @var ItemTransactionIDArrayType $ItemTransactionIDArray
	var $ItemTransactionIDArray;
	// @var OrderIDArrayType $OrderIDArray
	var $OrderIDArray;
	// end props

/**
 *

 * @return ItemTransactionIDArrayType
 */
	function getItemTransactionIDArray()
	{
		return $this->ItemTransactionIDArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemTransactionIDArray($value)
	{
		$this->ItemTransactionIDArray = $value;
	}
/**
 *

 * @return OrderIDArrayType
 */
	function getOrderIDArray()
	{
		return $this->OrderIDArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrderIDArray($value)
	{
		$this->OrderIDArray = $value;
	}
/**
 *

 * @return 
 */
	function GetOrderTransactionsRequestType()
	{
		$this->AbstractRequestType('GetOrderTransactionsRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemTransactionIDArray' =>
				array(
					'required' => false,
					'type' => 'ItemTransactionIDArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'OrderIDArray' =>
				array(
					'required' => false,
					'type' => 'OrderIDArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
