<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetOrderTransactionsResponseType.php,v 1.1.1.1 2006/12/22 14:38:01 gswkaiser Exp $
// $Log: GetOrderTransactionsResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:01  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';
require_once 'OrderArrayType.php';

class GetOrderTransactionsResponseType extends AbstractResponseType
{
	// start props
	// @var OrderArrayType $OrderArray
	var $OrderArray;
	// end props

/**
 *

 * @return OrderArrayType
 */
	function getOrderArray()
	{
		return $this->OrderArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrderArray($value)
	{
		$this->OrderArray = $value;
	}
/**
 *

 * @return 
 */
	function GetOrderTransactionsResponseType()
	{
		$this->AbstractResponseType('GetOrderTransactionsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'OrderArray' =>
				array(
					'required' => false,
					'type' => 'OrderArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
