<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetPictureManagerOptionsRequestType.php,v 1.1.1.1 2006/12/22 14:38:01 gswkaiser Exp $
// $Log: GetPictureManagerOptionsRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:01  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class GetPictureManagerOptionsRequestType extends AbstractRequestType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function GetPictureManagerOptionsRequestType()
	{
		$this->AbstractRequestType('GetPictureManagerOptionsRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
