<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetRuNameResponseType.php,v 1.1.1.1 2006/12/22 14:38:04 gswkaiser Exp $
// $Log: GetRuNameResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:04  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class GetRuNameResponseType extends AbstractResponseType
{
	// start props
	// @var string $RuName
	var $RuName;
	// end props

/**
 *

 * @return string
 */
	function getRuName()
	{
		return $this->RuName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRuName($value)
	{
		$this->RuName = $value;
	}
/**
 *

 * @return 
 */
	function GetRuNameResponseType()
	{
		$this->AbstractResponseType('GetRuNameResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'RuName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
