<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetStoreCustomPageResponseType.php,v 1.1.1.1 2006/12/22 14:38:09 gswkaiser Exp $
// $Log: GetStoreCustomPageResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:09  gswkaiser
// no message
//
//
require_once 'StoreCustomPageArrayType.php';
require_once 'AbstractResponseType.php';

class GetStoreCustomPageResponseType extends AbstractResponseType
{
	// start props
	// @var StoreCustomPageArrayType $CustomPageArray
	var $CustomPageArray;
	// end props

/**
 *

 * @return StoreCustomPageArrayType
 */
	function getCustomPageArray()
	{
		return $this->CustomPageArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCustomPageArray($value)
	{
		$this->CustomPageArray = $value;
	}
/**
 *

 * @return 
 */
	function GetStoreCustomPageResponseType()
	{
		$this->AbstractResponseType('GetStoreCustomPageResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CustomPageArray' =>
				array(
					'required' => false,
					'type' => 'StoreCustomPageArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
