<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetTaxTableRequestType.php,v 1.1.1.1 2006/12/22 14:38:09 gswkaiser Exp $
// $Log: GetTaxTableRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:09  gswkaiser
// no message
//
//
require_once 'AbstractRequestType.php';

class GetTaxTableRequestType extends AbstractRequestType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function GetTaxTableRequestType()
	{
		$this->AbstractRequestType('GetTaxTableRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
