<?php
// autogenerated file 17.11.2006 13:29
// $Id: GetWantItNowPostResponseType.php,v 1.1.1.1 2006/12/22 14:38:11 gswkaiser Exp $
// $Log: GetWantItNowPostResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:11  gswkaiser
// no message
//
//
require_once 'WantItNowPostType.php';
require_once 'AbstractResponseType.php';

class GetWantItNowPostResponseType extends AbstractResponseType
{
	// start props
	// @var WantItNowPostType $WantItNowPost
	var $WantItNowPost;
	// end props

/**
 *

 * @return WantItNowPostType
 */
	function getWantItNowPost()
	{
		return $this->WantItNowPost;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setWantItNowPost($value)
	{
		$this->WantItNowPost = $value;
	}
/**
 *

 * @return 
 */
	function GetWantItNowPostResponseType()
	{
		$this->AbstractResponseType('GetWantItNowPostResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'WantItNowPost' =>
				array(
					'required' => false,
					'type' => 'WantItNowPostType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
