<?php
// autogenerated file 17.11.2006 13:29
// $Id: GranularityLevelCodeType.php,v 1.1.1.1 2006/12/22 14:38:11 gswkaiser Exp $
// $Log: GranularityLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:11  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class GranularityLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Coarse
	var $Coarse = 'Coarse';
	// @var string $Fine
	var $Fine = 'Fine';
	// @var string $Medium
	var $Medium = 'Medium';
	// end props

/**
 *

 * @return 
 */
	function GranularityLevelCodeType()
	{
		$this->EbatNs_FacetType('GranularityLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_GranularityLevelCodeType = new GranularityLevelCodeType();

?>
