<?php
// autogenerated file 17.11.2006 13:29
// $Id: InsuranceOptionCodeType.php,v 1.1.1.1 2006/12/22 14:38:11 gswkaiser Exp $
// $Log: InsuranceOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:11  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class InsuranceOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Optional
	var $Optional = 'Optional';
	// @var string $Required
	var $Required = 'Required';
	// @var string $NotOffered
	var $NotOffered = 'NotOffered';
	// @var string $IncludedInShippingHandling
	var $IncludedInShippingHandling = 'IncludedInShippingHandling';
	// @var string $NotOfferedOnSite
	var $NotOfferedOnSite = 'NotOfferedOnSite';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function InsuranceOptionCodeType()
	{
		$this->EbatNs_FacetType('InsuranceOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_InsuranceOptionCodeType = new InsuranceOptionCodeType();

?>
