<?php
// autogenerated file 17.11.2006 13:29
// $Id: InvocationStatusType.php,v 1.1.1.1 2006/12/22 14:38:12 gswkaiser Exp $
// $Log: InvocationStatusType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:12  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class InvocationStatusType extends EbatNs_FacetType
{
	// start props
	// @var string $InProgress
	var $InProgress = 'InProgress';
	// @var string $Success
	var $Success = 'Success';
	// @var string $Failure
	var $Failure = 'Failure';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function InvocationStatusType()
	{
		$this->EbatNs_FacetType('InvocationStatusType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_InvocationStatusType = new InvocationStatusType();

?>
