<?php
// autogenerated file 17.11.2006 13:29
// $Id: ItemLocationCodeType.php,v 1.1.1.1 2006/12/22 14:38:12 gswkaiser Exp $
// $Log: ItemLocationCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:12  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ItemLocationCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ItemAvailableIn
	var $ItemAvailableIn = 'ItemAvailableIn';
	// @var string $ItemLocatedIn
	var $ItemLocatedIn = 'ItemLocatedIn';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ItemLocationCodeType()
	{
		$this->EbatNs_FacetType('ItemLocationCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ItemLocationCodeType = new ItemLocationCodeType();

?>
