<?php
// autogenerated file 17.11.2006 13:29
// $Id: ItemFormatSortFilterCodeType.php,v 1.1.1.1 2006/12/22 14:38:12 gswkaiser Exp $
// $Log: ItemFormatSortFilterCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:12  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ItemFormatSortFilterCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ShowAnyItems
	var $ShowAnyItems = 'ShowAnyItems';
	// @var string $ShowItemsWithBINFirst
	var $ShowItemsWithBINFirst = 'ShowItemsWithBINFirst';
	// @var string $ShowOnlyItemsWithBIN
	var $ShowOnlyItemsWithBIN = 'ShowOnlyItemsWithBIN';
	// @var string $ShowOnlyStoreItems
	var $ShowOnlyStoreItems = 'ShowOnlyStoreItems';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ItemFormatSortFilterCodeType()
	{
		$this->EbatNs_FacetType('ItemFormatSortFilterCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ItemFormatSortFilterCodeType = new ItemFormatSortFilterCodeType();

?>
