<?php
// autogenerated file 17.11.2006 13:29
// $Id: ItemType.php,v 1.1.1.1 2006/12/22 14:38:16 gswkaiser Exp $
// $Log: ItemType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:16  gswkaiser
// no message
//
//
require_once 'ExternalProductIDType.php';
require_once 'ListingSubtypeEnum.php';
require_once 'CharityType.php';
require_once 'DescriptionReviseModeCodeType.php';
require_once 'HitCounterCodeType.php';
require_once 'SkypeOptionCodeType.php';
require_once 'UserType.php';
require_once 'SellingStatusType.php';
require_once 'ListingDetailsType.php';
require_once 'AttributeArrayType.php';
require_once 'CrossPromotionsType.php';
require_once 'ShippingDetailsType.php';
require_once 'ShippingTermsCodeType.php';
require_once 'SiteHostedPictureType.php';
require_once 'VATDetailsType.php';
require_once 'AmountType.php';
require_once 'CurrencyCodeType.php';
require_once 'CountryCodeType.php';
require_once 'LookupAttributeArrayType.php';
require_once 'VendorHostedPictureType.php';
require_once 'AttributeSetArrayType.php';
require_once 'PictureDetailsType.php';
require_once 'StorefrontType.php';
require_once 'ProductListingDetailsType.php';
require_once 'PaymentDetailsType.php';
require_once 'SearchDetailsType.php';
require_once 'ShippingOptionCodeType.php';
require_once 'SiteCodeType.php';
require_once 'GiftServicesCodeType.php';
require_once 'BestOfferDetailsType.php';
require_once 'BuyerProtectionCodeType.php';
require_once 'ReviseStatusType.php';
require_once 'AddressType.php';
require_once 'ListingDesignerType.php';
require_once 'BuyerPaymentMethodCodeType.php';
require_once 'ListingTypeCodeType.php';
require_once 'ListingEnhancementsCodeType.php';
require_once 'DistanceType.php';
require_once 'ItemIDType.php';
require_once 'BiddingDetailsType.php';
require_once 'SkypeContactOptionCodeType.php';
require_once 'ListingCheckoutRedirectPreferenceType.php';
require_once 'BuyerRequirementsType.php';
require_once 'DigitalDeliveryDetailsType.php';
require_once 'LiveAuctionDetailsType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'SKUType.php';
require_once 'ProximitySearchDetailsType.php';
require_once 'UUIDType.php';
require_once 'ShippingRegionCodeType.php';
require_once 'ExpressDetailsType.php';
require_once 'CategoryType.php';

class ItemType extends EbatNs_ComplexType
{
	// start props
	// @var string $ApplicationData
	var $ApplicationData;
	// @var AttributeSetArrayType $AttributeSetArray
	var $AttributeSetArray;
	// @var AttributeArrayType $AttributeArray
	var $AttributeArray;
	// @var LookupAttributeArrayType $LookupAttributeArray
	var $LookupAttributeArray;
	// @var boolean $ApplyShippingDiscount
	var $ApplyShippingDiscount;
	// @var boolean $AutoPay
	var $AutoPay;
	// @var PaymentDetailsType $PaymentDetails
	var $PaymentDetails;
	// @var BiddingDetailsType $BiddingDetails
	var $BiddingDetails;
	// @var boolean $MotorsGermanySearchable
	var $MotorsGermanySearchable;
	// @var BuyerProtectionCodeType $BuyerProtection
	var $BuyerProtection;
	// @var AmountType $BuyItNowPrice
	var $BuyItNowPrice;
	// @var boolean $CategoryMappingAllowed
	var $CategoryMappingAllowed;
	// @var CharityType $Charity
	var $Charity;
	// @var CountryCodeType $Country
	var $Country;
	// @var CrossPromotionsType $CrossPromotion
	var $CrossPromotion;
	// @var CurrencyCodeType $Currency
	var $Currency;
	// @var string $Description
	var $Description;
	// @var DescriptionReviseModeCodeType $DescriptionReviseMode
	var $DescriptionReviseMode;
	// @var DistanceType $Distance
	var $Distance;
	// @var string $FinanceOfferID
	var $FinanceOfferID;
	// @var int $GiftIcon
	var $GiftIcon;
	// @var GiftServicesCodeType $GiftServices
	var $GiftServices;
	// @var HitCounterCodeType $HitCounter
	var $HitCounter;
	// @var ItemIDType $ItemID
	var $ItemID;
	// @var ListingDetailsType $ListingDetails
	var $ListingDetails;
	// @var ListingDesignerType $ListingDesigner
	var $ListingDesigner;
	// @var token $ListingDuration
	var $ListingDuration;
	// @var ListingEnhancementsCodeType $ListingEnhancement
	var $ListingEnhancement;
	// @var ListingTypeCodeType $ListingType
	var $ListingType;
	// @var ListingSubtypeEnum $ListingSubtype
	var $ListingSubtype;
	// @var string $Location
	var $Location;
	// @var int $LotSize
	var $LotSize;
	// @var boolean $NowAndNew
	var $NowAndNew;
	// @var string $PartnerCode
	var $PartnerCode;
	// @var string $PartnerName
	var $PartnerName;
	// @var BuyerPaymentMethodCodeType $PaymentMethods
	var $PaymentMethods;
	// @var string $PayPalEmailAddress
	var $PayPalEmailAddress;
	// @var CategoryType $PrimaryCategory
	var $PrimaryCategory;
	// @var boolean $PrivateListing
	var $PrivateListing;
	// @var ProductListingDetailsType $ProductListingDetails
	var $ProductListingDetails;
	// @var ProximitySearchDetailsType $ProximitySearchDetails
	var $ProximitySearchDetails;
	// @var int $Quantity
	var $Quantity;
	// @var string $PrivateNotes
	var $PrivateNotes;
	// @var string $RegionID
	var $RegionID;
	// @var boolean $RelistLink
	var $RelistLink;
	// @var AmountType $ReservePrice
	var $ReservePrice;
	// @var ReviseStatusType $ReviseStatus
	var $ReviseStatus;
	// @var dateTime $ScheduleTime
	var $ScheduleTime;
	// @var CategoryType $SecondaryCategory
	var $SecondaryCategory;
	// @var CategoryType $FreeAddedCategory
	var $FreeAddedCategory;
	// @var SiteHostedPictureType $SiteHostedPicture
	var $SiteHostedPicture;
	// @var UserType $Seller
	var $Seller;
	// @var SellingStatusType $SellingStatus
	var $SellingStatus;
	// @var ShippingOptionCodeType $ShippingOption
	var $ShippingOption;
	// @var ShippingDetailsType $ShippingDetails
	var $ShippingDetails;
	// @var ShippingRegionCodeType $ShippingRegions
	var $ShippingRegions;
	// @var ShippingTermsCodeType $ShippingTerms
	var $ShippingTerms;
	// @var string $ShipToLocations
	var $ShipToLocations;
	// @var SiteCodeType $Site
	var $Site;
	// @var AmountType $StartPrice
	var $StartPrice;
	// @var StorefrontType $Storefront
	var $Storefront;
	// @var string $SubTitle
	var $SubTitle;
	// @var duration $TimeLeft
	var $TimeLeft;
	// @var string $Title
	var $Title;
	// @var UUIDType $UUID
	var $UUID;
	// @var VATDetailsType $VATDetails
	var $VATDetails;
	// @var VendorHostedPictureType $VendorHostedPicture
	var $VendorHostedPicture;
	// @var string $SellerVacationNote
	var $SellerVacationNote;
	// @var long $WatchCount
	var $WatchCount;
	// @var long $HitCount
	var $HitCount;
	// @var boolean $DisableBuyerRequirements
	var $DisableBuyerRequirements;
	// @var BuyerRequirementsType $BuyerRequirements
	var $BuyerRequirements;
	// @var BestOfferDetailsType $BestOfferDetails
	var $BestOfferDetails;
	// @var boolean $AnythingPoints
	var $AnythingPoints;
	// @var LiveAuctionDetailsType $LiveAuctionDetails
	var $LiveAuctionDetails;
	// @var boolean $LocationDefaulted
	var $LocationDefaulted;
	// @var boolean $ThirdPartyCheckout
	var $ThirdPartyCheckout;
	// @var boolean $UseTaxTable
	var $UseTaxTable;
	// @var boolean $GetItFast
	var $GetItFast;
	// @var boolean $BuyerResponsibleForShipping
	var $BuyerResponsibleForShipping;
	// @var boolean $LimitedWarrantyEligible
	var $LimitedWarrantyEligible;
	// @var string $eBayNotes
	var $eBayNotes;
	// @var long $QuestionCount
	var $QuestionCount;
	// @var boolean $Relisted
	var $Relisted;
	// @var int $QuantityAvailable
	var $QuantityAvailable;
	// @var SKUType $SKU
	var $SKU;
	// @var boolean $CategoryBasedAttributesPrefill
	var $CategoryBasedAttributesPrefill;
	// @var SearchDetailsType $SearchDetails
	var $SearchDetails;
	// @var string $PostalCode
	var $PostalCode;
	// @var boolean $ShippingTermsInDescription
	var $ShippingTermsInDescription;
	// @var ExternalProductIDType $ExternalProductID
	var $ExternalProductID;
	// @var string $SellerInventoryID
	var $SellerInventoryID;
	// @var PictureDetailsType $PictureDetails
	var $PictureDetails;
	// @var DigitalDeliveryDetailsType $DigitalDeliveryDetails
	var $DigitalDeliveryDetails;
	// @var int $DispatchTimeMax
	var $DispatchTimeMax;
	// @var boolean $SkypeEnabled
	var $SkypeEnabled;
	// @var string $SkypeID
	var $SkypeID;
	// @var SkypeOptionCodeType $SkypeOption
	var $SkypeOption;
	// @var SkypeContactOptionCodeType $SkypeContactOption
	var $SkypeContactOption;
	// @var boolean $BestOfferEnabled
	var $BestOfferEnabled;
	// @var boolean $LocalListing
	var $LocalListing;
	// @var boolean $ThirdPartyCheckoutIntegration
	var $ThirdPartyCheckoutIntegration;
	// @var boolean $ExpressOptOut
	var $ExpressOptOut;
	// @var ListingCheckoutRedirectPreferenceType $ListingCheckoutRedirectPreference
	var $ListingCheckoutRedirectPreference;
	// @var ExpressDetailsType $ExpressDetails
	var $ExpressDetails;
	// @var AddressType $SellerContactDetails
	var $SellerContactDetails;
	// @var long $TotalQuestionCount
	var $TotalQuestionCount;
	// @var boolean $ProxyItem
	var $ProxyItem;
	// end props

/**
 *

 * @return string
 */
	function getApplicationData()
	{
		return $this->ApplicationData;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setApplicationData($value)
	{
		$this->ApplicationData = $value;
	}
/**
 *

 * @return AttributeSetArrayType
 */
	function getAttributeSetArray()
	{
		return $this->AttributeSetArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAttributeSetArray($value)
	{
		$this->AttributeSetArray = $value;
	}
/**
 *

 * @return AttributeArrayType
 */
	function getAttributeArray()
	{
		return $this->AttributeArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAttributeArray($value)
	{
		$this->AttributeArray = $value;
	}
/**
 *

 * @return LookupAttributeArrayType
 */
	function getLookupAttributeArray()
	{
		return $this->LookupAttributeArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLookupAttributeArray($value)
	{
		$this->LookupAttributeArray = $value;
	}
/**
 *

 * @return boolean
 */
	function getApplyShippingDiscount()
	{
		return $this->ApplyShippingDiscount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setApplyShippingDiscount($value)
	{
		$this->ApplyShippingDiscount = $value;
	}
/**
 *

 * @return boolean
 */
	function getAutoPay()
	{
		return $this->AutoPay;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutoPay($value)
	{
		$this->AutoPay = $value;
	}
/**
 *

 * @return PaymentDetailsType
 */
	function getPaymentDetails()
	{
		return $this->PaymentDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaymentDetails($value)
	{
		$this->PaymentDetails = $value;
	}
/**
 *

 * @return BiddingDetailsType
 */
	function getBiddingDetails()
	{
		return $this->BiddingDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBiddingDetails($value)
	{
		$this->BiddingDetails = $value;
	}
/**
 *

 * @return boolean
 */
	function getMotorsGermanySearchable()
	{
		return $this->MotorsGermanySearchable;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMotorsGermanySearchable($value)
	{
		$this->MotorsGermanySearchable = $value;
	}
/**
 *

 * @return BuyerProtectionCodeType
 */
	function getBuyerProtection()
	{
		return $this->BuyerProtection;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBuyerProtection($value)
	{
		$this->BuyerProtection = $value;
	}
/**
 *

 * @return AmountType
 */
	function getBuyItNowPrice()
	{
		return $this->BuyItNowPrice;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBuyItNowPrice($value)
	{
		$this->BuyItNowPrice = $value;
	}
/**
 *

 * @return boolean
 */
	function getCategoryMappingAllowed()
	{
		return $this->CategoryMappingAllowed;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryMappingAllowed($value)
	{
		$this->CategoryMappingAllowed = $value;
	}
/**
 *

 * @return CharityType
 */
	function getCharity()
	{
		return $this->Charity;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCharity($value)
	{
		$this->Charity = $value;
	}
/**
 *

 * @return CountryCodeType
 */
	function getCountry()
	{
		return $this->Country;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCountry($value)
	{
		$this->Country = $value;
	}
/**
 *

 * @return CrossPromotionsType
 */
	function getCrossPromotion()
	{
		return $this->CrossPromotion;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCrossPromotion($value)
	{
		$this->CrossPromotion = $value;
	}
/**
 *

 * @return CurrencyCodeType
 */
	function getCurrency()
	{
		return $this->Currency;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCurrency($value)
	{
		$this->Currency = $value;
	}
/**
 *

 * @return string
 */
	function getDescription()
	{
		return $this->Description;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDescription($value)
	{
		$this->Description = $value;
	}
/**
 *

 * @return DescriptionReviseModeCodeType
 */
	function getDescriptionReviseMode()
	{
		return $this->DescriptionReviseMode;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDescriptionReviseMode($value)
	{
		$this->DescriptionReviseMode = $value;
	}
/**
 *

 * @return DistanceType
 */
	function getDistance()
	{
		return $this->Distance;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDistance($value)
	{
		$this->Distance = $value;
	}
/**
 *

 * @return string
 */
	function getFinanceOfferID()
	{
		return $this->FinanceOfferID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFinanceOfferID($value)
	{
		$this->FinanceOfferID = $value;
	}
/**
 *

 * @return int
 */
	function getGiftIcon()
	{
		return $this->GiftIcon;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGiftIcon($value)
	{
		$this->GiftIcon = $value;
	}
/**
 *

 * @return GiftServicesCodeType
 * @param  $index 
 */
	function getGiftServices($index = null)
	{
		if ($index) {
		return $this->GiftServices[$index];
	} else {
		return $this->GiftServices;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setGiftServices($value, $index = null)
	{
		if ($index) {
	$this->GiftServices[$index] = $value;
	} else {
	$this->GiftServices = $value;
	}

	}
/**
 *

 * @return HitCounterCodeType
 */
	function getHitCounter()
	{
		return $this->HitCounter;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHitCounter($value)
	{
		$this->HitCounter = $value;
	}
/**
 *

 * @return ItemIDType
 */
	function getItemID()
	{
		return $this->ItemID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
/**
 *

 * @return ListingDetailsType
 */
	function getListingDetails()
	{
		return $this->ListingDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingDetails($value)
	{
		$this->ListingDetails = $value;
	}
/**
 *

 * @return ListingDesignerType
 */
	function getListingDesigner()
	{
		return $this->ListingDesigner;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingDesigner($value)
	{
		$this->ListingDesigner = $value;
	}
/**
 *

 * @return token
 */
	function getListingDuration()
	{
		return $this->ListingDuration;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingDuration($value)
	{
		$this->ListingDuration = $value;
	}
/**
 *

 * @return ListingEnhancementsCodeType
 * @param  $index 
 */
	function getListingEnhancement($index = null)
	{
		if ($index) {
		return $this->ListingEnhancement[$index];
	} else {
		return $this->ListingEnhancement;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setListingEnhancement($value, $index = null)
	{
		if ($index) {
	$this->ListingEnhancement[$index] = $value;
	} else {
	$this->ListingEnhancement = $value;
	}

	}
/**
 *

 * @return ListingTypeCodeType
 */
	function getListingType()
	{
		return $this->ListingType;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingType($value)
	{
		$this->ListingType = $value;
	}
/**
 *

 * @return ListingSubtypeEnum
 */
	function getListingSubtype()
	{
		return $this->ListingSubtype;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingSubtype($value)
	{
		$this->ListingSubtype = $value;
	}
/**
 *

 * @return string
 */
	function getLocation()
	{
		return $this->Location;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocation($value)
	{
		$this->Location = $value;
	}
/**
 *

 * @return int
 */
	function getLotSize()
	{
		return $this->LotSize;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLotSize($value)
	{
		$this->LotSize = $value;
	}
/**
 *

 * @return boolean
 */
	function getNowAndNew()
	{
		return $this->NowAndNew;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setNowAndNew($value)
	{
		$this->NowAndNew = $value;
	}
/**
 *

 * @return string
 */
	function getPartnerCode()
	{
		return $this->PartnerCode;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPartnerCode($value)
	{
		$this->PartnerCode = $value;
	}
/**
 *

 * @return string
 */
	function getPartnerName()
	{
		return $this->PartnerName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPartnerName($value)
	{
		$this->PartnerName = $value;
	}
/**
 *

 * @return BuyerPaymentMethodCodeType
 * @param  $index 
 */
	function getPaymentMethods($index = null)
	{
		if ($index) {
		return $this->PaymentMethods[$index];
	} else {
		return $this->PaymentMethods;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setPaymentMethods($value, $index = null)
	{
		if ($index) {
	$this->PaymentMethods[$index] = $value;
	} else {
	$this->PaymentMethods = $value;
	}

	}
/**
 *

 * @return string
 */
	function getPayPalEmailAddress()
	{
		return $this->PayPalEmailAddress;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPayPalEmailAddress($value)
	{
		$this->PayPalEmailAddress = $value;
	}
/**
 *

 * @return CategoryType
 */
	function getPrimaryCategory()
	{
		return $this->PrimaryCategory;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPrimaryCategory($value)
	{
		$this->PrimaryCategory = $value;
	}
/**
 *

 * @return boolean
 */
	function getPrivateListing()
	{
		return $this->PrivateListing;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPrivateListing($value)
	{
		$this->PrivateListing = $value;
	}
/**
 *

 * @return ProductListingDetailsType
 */
	function getProductListingDetails()
	{
		return $this->ProductListingDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProductListingDetails($value)
	{
		$this->ProductListingDetails = $value;
	}
/**
 *

 * @return ProximitySearchDetailsType
 */
	function getProximitySearchDetails()
	{
		return $this->ProximitySearchDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProximitySearchDetails($value)
	{
		$this->ProximitySearchDetails = $value;
	}
/**
 *

 * @return int
 */
	function getQuantity()
	{
		return $this->Quantity;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setQuantity($value)
	{
		$this->Quantity = $value;
	}
/**
 *

 * @return string
 */
	function getPrivateNotes()
	{
		return $this->PrivateNotes;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPrivateNotes($value)
	{
		$this->PrivateNotes = $value;
	}
/**
 *

 * @return string
 */
	function getRegionID()
	{
		return $this->RegionID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRegionID($value)
	{
		$this->RegionID = $value;
	}
/**
 *

 * @return boolean
 */
	function getRelistLink()
	{
		return $this->RelistLink;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelistLink($value)
	{
		$this->RelistLink = $value;
	}
/**
 *

 * @return AmountType
 */
	function getReservePrice()
	{
		return $this->ReservePrice;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReservePrice($value)
	{
		$this->ReservePrice = $value;
	}
/**
 *

 * @return ReviseStatusType
 */
	function getReviseStatus()
	{
		return $this->ReviseStatus;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReviseStatus($value)
	{
		$this->ReviseStatus = $value;
	}
/**
 *

 * @return dateTime
 */
	function getScheduleTime()
	{
		return $this->ScheduleTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setScheduleTime($value)
	{
		$this->ScheduleTime = $value;
	}
/**
 *

 * @return CategoryType
 */
	function getSecondaryCategory()
	{
		return $this->SecondaryCategory;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSecondaryCategory($value)
	{
		$this->SecondaryCategory = $value;
	}
/**
 *

 * @return CategoryType
 */
	function getFreeAddedCategory()
	{
		return $this->FreeAddedCategory;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFreeAddedCategory($value)
	{
		$this->FreeAddedCategory = $value;
	}
/**
 *

 * @return SiteHostedPictureType
 */
	function getSiteHostedPicture()
	{
		return $this->SiteHostedPicture;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSiteHostedPicture($value)
	{
		$this->SiteHostedPicture = $value;
	}
/**
 *

 * @return UserType
 */
	function getSeller()
	{
		return $this->Seller;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSeller($value)
	{
		$this->Seller = $value;
	}
/**
 *

 * @return SellingStatusType
 */
	function getSellingStatus()
	{
		return $this->SellingStatus;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellingStatus($value)
	{
		$this->SellingStatus = $value;
	}
/**
 *

 * @return ShippingOptionCodeType
 */
	function getShippingOption()
	{
		return $this->ShippingOption;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingOption($value)
	{
		$this->ShippingOption = $value;
	}
/**
 *

 * @return ShippingDetailsType
 */
	function getShippingDetails()
	{
		return $this->ShippingDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingDetails($value)
	{
		$this->ShippingDetails = $value;
	}
/**
 *

 * @return ShippingRegionCodeType
 * @param  $index 
 */
	function getShippingRegions($index = null)
	{
		if ($index) {
		return $this->ShippingRegions[$index];
	} else {
		return $this->ShippingRegions;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setShippingRegions($value, $index = null)
	{
		if ($index) {
	$this->ShippingRegions[$index] = $value;
	} else {
	$this->ShippingRegions = $value;
	}

	}
/**
 *

 * @return ShippingTermsCodeType
 */
	function getShippingTerms()
	{
		return $this->ShippingTerms;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingTerms($value)
	{
		$this->ShippingTerms = $value;
	}
/**
 *

 * @return string
 * @param  $index 
 */
	function getShipToLocations($index = null)
	{
		if ($index) {
		return $this->ShipToLocations[$index];
	} else {
		return $this->ShipToLocations;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setShipToLocations($value, $index = null)
	{
		if ($index) {
	$this->ShipToLocations[$index] = $value;
	} else {
	$this->ShipToLocations = $value;
	}

	}
/**
 *

 * @return SiteCodeType
 */
	function getSite()
	{
		return $this->Site;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSite($value)
	{
		$this->Site = $value;
	}
/**
 *

 * @return AmountType
 */
	function getStartPrice()
	{
		return $this->StartPrice;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStartPrice($value)
	{
		$this->StartPrice = $value;
	}
/**
 *

 * @return StorefrontType
 */
	function getStorefront()
	{
		return $this->Storefront;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStorefront($value)
	{
		$this->Storefront = $value;
	}
/**
 *

 * @return string
 */
	function getSubTitle()
	{
		return $this->SubTitle;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSubTitle($value)
	{
		$this->SubTitle = $value;
	}
/**
 *

 * @return duration
 */
	function getTimeLeft()
	{
		return $this->TimeLeft;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTimeLeft($value)
	{
		$this->TimeLeft = $value;
	}
/**
 *

 * @return string
 */
	function getTitle()
	{
		return $this->Title;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTitle($value)
	{
		$this->Title = $value;
	}
/**
 *

 * @return UUIDType
 */
	function getUUID()
	{
		return $this->UUID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setUUID($value)
	{
		$this->UUID = $value;
	}
/**
 *

 * @return VATDetailsType
 */
	function getVATDetails()
	{
		return $this->VATDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVATDetails($value)
	{
		$this->VATDetails = $value;
	}
/**
 *

 * @return VendorHostedPictureType
 */
	function getVendorHostedPicture()
	{
		return $this->VendorHostedPicture;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVendorHostedPicture($value)
	{
		$this->VendorHostedPicture = $value;
	}
/**
 *

 * @return string
 */
	function getSellerVacationNote()
	{
		return $this->SellerVacationNote;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellerVacationNote($value)
	{
		$this->SellerVacationNote = $value;
	}
/**
 *

 * @return long
 */
	function getWatchCount()
	{
		return $this->WatchCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setWatchCount($value)
	{
		$this->WatchCount = $value;
	}
/**
 *

 * @return long
 */
	function getHitCount()
	{
		return $this->HitCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHitCount($value)
	{
		$this->HitCount = $value;
	}
/**
 *

 * @return boolean
 */
	function getDisableBuyerRequirements()
	{
		return $this->DisableBuyerRequirements;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDisableBuyerRequirements($value)
	{
		$this->DisableBuyerRequirements = $value;
	}
/**
 *

 * @return BuyerRequirementsType
 */
	function getBuyerRequirements()
	{
		return $this->BuyerRequirements;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBuyerRequirements($value)
	{
		$this->BuyerRequirements = $value;
	}
/**
 *

 * @return BestOfferDetailsType
 */
	function getBestOfferDetails()
	{
		return $this->BestOfferDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferDetails($value)
	{
		$this->BestOfferDetails = $value;
	}
/**
 *

 * @return boolean
 */
	function getAnythingPoints()
	{
		return $this->AnythingPoints;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAnythingPoints($value)
	{
		$this->AnythingPoints = $value;
	}
/**
 *

 * @return LiveAuctionDetailsType
 */
	function getLiveAuctionDetails()
	{
		return $this->LiveAuctionDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLiveAuctionDetails($value)
	{
		$this->LiveAuctionDetails = $value;
	}
/**
 *

 * @return boolean
 */
	function getLocationDefaulted()
	{
		return $this->LocationDefaulted;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocationDefaulted($value)
	{
		$this->LocationDefaulted = $value;
	}
/**
 *

 * @return boolean
 */
	function getThirdPartyCheckout()
	{
		return $this->ThirdPartyCheckout;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setThirdPartyCheckout($value)
	{
		$this->ThirdPartyCheckout = $value;
	}
/**
 *

 * @return boolean
 */
	function getUseTaxTable()
	{
		return $this->UseTaxTable;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setUseTaxTable($value)
	{
		$this->UseTaxTable = $value;
	}
/**
 *

 * @return boolean
 */
	function getGetItFast()
	{
		return $this->GetItFast;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGetItFast($value)
	{
		$this->GetItFast = $value;
	}
/**
 *

 * @return boolean
 */
	function getBuyerResponsibleForShipping()
	{
		return $this->BuyerResponsibleForShipping;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBuyerResponsibleForShipping($value)
	{
		$this->BuyerResponsibleForShipping = $value;
	}
/**
 *

 * @return boolean
 */
	function getLimitedWarrantyEligible()
	{
		return $this->LimitedWarrantyEligible;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLimitedWarrantyEligible($value)
	{
		$this->LimitedWarrantyEligible = $value;
	}
/**
 *

 * @return string
 */
	function geteBayNotes()
	{
		return $this->eBayNotes;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function seteBayNotes($value)
	{
		$this->eBayNotes = $value;
	}
/**
 *

 * @return long
 */
	function getQuestionCount()
	{
		return $this->QuestionCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setQuestionCount($value)
	{
		$this->QuestionCount = $value;
	}
/**
 *

 * @return boolean
 */
	function getRelisted()
	{
		return $this->Relisted;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelisted($value)
	{
		$this->Relisted = $value;
	}
/**
 *

 * @return int
 */
	function getQuantityAvailable()
	{
		return $this->QuantityAvailable;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setQuantityAvailable($value)
	{
		$this->QuantityAvailable = $value;
	}
/**
 *

 * @return SKUType
 */
	function getSKU()
	{
		return $this->SKU;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSKU($value)
	{
		$this->SKU = $value;
	}
/**
 *

 * @return boolean
 */
	function getCategoryBasedAttributesPrefill()
	{
		return $this->CategoryBasedAttributesPrefill;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryBasedAttributesPrefill($value)
	{
		$this->CategoryBasedAttributesPrefill = $value;
	}
/**
 *

 * @return SearchDetailsType
 */
	function getSearchDetails()
	{
		return $this->SearchDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSearchDetails($value)
	{
		$this->SearchDetails = $value;
	}
/**
 *

 * @return string
 */
	function getPostalCode()
	{
		return $this->PostalCode;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPostalCode($value)
	{
		$this->PostalCode = $value;
	}
/**
 *

 * @return boolean
 */
	function getShippingTermsInDescription()
	{
		return $this->ShippingTermsInDescription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingTermsInDescription($value)
	{
		$this->ShippingTermsInDescription = $value;
	}
/**
 *

 * @return ExternalProductIDType
 */
	function getExternalProductID()
	{
		return $this->ExternalProductID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExternalProductID($value)
	{
		$this->ExternalProductID = $value;
	}
/**
 *

 * @return string
 */
	function getSellerInventoryID()
	{
		return $this->SellerInventoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellerInventoryID($value)
	{
		$this->SellerInventoryID = $value;
	}
/**
 *

 * @return PictureDetailsType
 */
	function getPictureDetails()
	{
		return $this->PictureDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPictureDetails($value)
	{
		$this->PictureDetails = $value;
	}
/**
 *

 * @return DigitalDeliveryDetailsType
 */
	function getDigitalDeliveryDetails()
	{
		return $this->DigitalDeliveryDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDigitalDeliveryDetails($value)
	{
		$this->DigitalDeliveryDetails = $value;
	}
/**
 *

 * @return int
 */
	function getDispatchTimeMax()
	{
		return $this->DispatchTimeMax;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDispatchTimeMax($value)
	{
		$this->DispatchTimeMax = $value;
	}
/**
 *

 * @return boolean
 */
	function getSkypeEnabled()
	{
		return $this->SkypeEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSkypeEnabled($value)
	{
		$this->SkypeEnabled = $value;
	}
/**
 *

 * @return string
 */
	function getSkypeID()
	{
		return $this->SkypeID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSkypeID($value)
	{
		$this->SkypeID = $value;
	}
/**
 *

 * @return SkypeOptionCodeType
 * @param  $index 
 */
	function getSkypeOption($index = null)
	{
		if ($index) {
		return $this->SkypeOption[$index];
	} else {
		return $this->SkypeOption;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setSkypeOption($value, $index = null)
	{
		if ($index) {
	$this->SkypeOption[$index] = $value;
	} else {
	$this->SkypeOption = $value;
	}

	}
/**
 *

 * @return SkypeContactOptionCodeType
 * @param  $index 
 */
	function getSkypeContactOption($index = null)
	{
		if ($index) {
		return $this->SkypeContactOption[$index];
	} else {
		return $this->SkypeContactOption;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setSkypeContactOption($value, $index = null)
	{
		if ($index) {
	$this->SkypeContactOption[$index] = $value;
	} else {
	$this->SkypeContactOption = $value;
	}

	}
/**
 *

 * @return boolean
 */
	function getBestOfferEnabled()
	{
		return $this->BestOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferEnabled($value)
	{
		$this->BestOfferEnabled = $value;
	}
/**
 *

 * @return boolean
 */
	function getLocalListing()
	{
		return $this->LocalListing;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalListing($value)
	{
		$this->LocalListing = $value;
	}
/**
 *

 * @return boolean
 */
	function getThirdPartyCheckoutIntegration()
	{
		return $this->ThirdPartyCheckoutIntegration;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setThirdPartyCheckoutIntegration($value)
	{
		$this->ThirdPartyCheckoutIntegration = $value;
	}
/**
 *

 * @return boolean
 */
	function getExpressOptOut()
	{
		return $this->ExpressOptOut;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpressOptOut($value)
	{
		$this->ExpressOptOut = $value;
	}
/**
 *

 * @return ListingCheckoutRedirectPreferenceType
 */
	function getListingCheckoutRedirectPreference()
	{
		return $this->ListingCheckoutRedirectPreference;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingCheckoutRedirectPreference($value)
	{
		$this->ListingCheckoutRedirectPreference = $value;
	}
/**
 *

 * @return ExpressDetailsType
 */
	function getExpressDetails()
	{
		return $this->ExpressDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpressDetails($value)
	{
		$this->ExpressDetails = $value;
	}
/**
 *

 * @return AddressType
 */
	function getSellerContactDetails()
	{
		return $this->SellerContactDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellerContactDetails($value)
	{
		$this->SellerContactDetails = $value;
	}
/**
 *

 * @return long
 */
	function getTotalQuestionCount()
	{
		return $this->TotalQuestionCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTotalQuestionCount($value)
	{
		$this->TotalQuestionCount = $value;
	}
/**
 *

 * @return boolean
 */
	function getProxyItem()
	{
		return $this->ProxyItem;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProxyItem($value)
	{
		$this->ProxyItem = $value;
	}
/**
 *

 * @return 
 */
	function ItemType()
	{
		$this->EbatNs_ComplexType('ItemType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ApplicationData' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AttributeSetArray' =>
				array(
					'required' => false,
					'type' => 'AttributeSetArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AttributeArray' =>
				array(
					'required' => false,
					'type' => 'AttributeArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LookupAttributeArray' =>
				array(
					'required' => false,
					'type' => 'LookupAttributeArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ApplyShippingDiscount' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AutoPay' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaymentDetails' =>
				array(
					'required' => false,
					'type' => 'PaymentDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BiddingDetails' =>
				array(
					'required' => false,
					'type' => 'BiddingDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MotorsGermanySearchable' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BuyerProtection' =>
				array(
					'required' => false,
					'type' => 'BuyerProtectionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BuyItNowPrice' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CategoryMappingAllowed' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Charity' =>
				array(
					'required' => false,
					'type' => 'CharityType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Country' =>
				array(
					'required' => false,
					'type' => 'CountryCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CrossPromotion' =>
				array(
					'required' => false,
					'type' => 'CrossPromotionsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Currency' =>
				array(
					'required' => false,
					'type' => 'CurrencyCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Description' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DescriptionReviseMode' =>
				array(
					'required' => false,
					'type' => 'DescriptionReviseModeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Distance' =>
				array(
					'required' => false,
					'type' => 'DistanceType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FinanceOfferID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'GiftIcon' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'GiftServices' =>
				array(
					'required' => false,
					'type' => 'GiftServicesCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'HitCounter' =>
				array(
					'required' => false,
					'type' => 'HitCounterCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ItemID' =>
				array(
					'required' => false,
					'type' => 'ItemIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingDetails' =>
				array(
					'required' => false,
					'type' => 'ListingDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingDesigner' =>
				array(
					'required' => false,
					'type' => 'ListingDesignerType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingDuration' =>
				array(
					'required' => false,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingEnhancement' =>
				array(
					'required' => false,
					'type' => 'ListingEnhancementsCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'ListingType' =>
				array(
					'required' => false,
					'type' => 'ListingTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingSubtype' =>
				array(
					'required' => false,
					'type' => 'ListingSubtypeEnum',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Location' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LotSize' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'NowAndNew' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PartnerCode' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PartnerName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaymentMethods' =>
				array(
					'required' => false,
					'type' => 'BuyerPaymentMethodCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'PayPalEmailAddress' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PrimaryCategory' =>
				array(
					'required' => false,
					'type' => 'CategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PrivateListing' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProductListingDetails' =>
				array(
					'required' => false,
					'type' => 'ProductListingDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProximitySearchDetails' =>
				array(
					'required' => false,
					'type' => 'ProximitySearchDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Quantity' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PrivateNotes' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RegionID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RelistLink' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReservePrice' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReviseStatus' =>
				array(
					'required' => false,
					'type' => 'ReviseStatusType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ScheduleTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SecondaryCategory' =>
				array(
					'required' => false,
					'type' => 'CategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FreeAddedCategory' =>
				array(
					'required' => false,
					'type' => 'CategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SiteHostedPicture' =>
				array(
					'required' => false,
					'type' => 'SiteHostedPictureType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Seller' =>
				array(
					'required' => false,
					'type' => 'UserType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellingStatus' =>
				array(
					'required' => false,
					'type' => 'SellingStatusType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShippingOption' =>
				array(
					'required' => false,
					'type' => 'ShippingOptionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShippingDetails' =>
				array(
					'required' => false,
					'type' => 'ShippingDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShippingRegions' =>
				array(
					'required' => false,
					'type' => 'ShippingRegionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'ShippingTerms' =>
				array(
					'required' => false,
					'type' => 'ShippingTermsCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShipToLocations' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				),
				'Site' =>
				array(
					'required' => false,
					'type' => 'SiteCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StartPrice' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Storefront' =>
				array(
					'required' => false,
					'type' => 'StorefrontType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SubTitle' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TimeLeft' =>
				array(
					'required' => false,
					'type' => 'duration',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Title' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'UUID' =>
				array(
					'required' => false,
					'type' => 'UUIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VATDetails' =>
				array(
					'required' => false,
					'type' => 'VATDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VendorHostedPicture' =>
				array(
					'required' => false,
					'type' => 'VendorHostedPictureType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellerVacationNote' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'WatchCount' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'HitCount' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DisableBuyerRequirements' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BuyerRequirements' =>
				array(
					'required' => false,
					'type' => 'BuyerRequirementsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferDetails' =>
				array(
					'required' => false,
					'type' => 'BestOfferDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AnythingPoints' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LiveAuctionDetails' =>
				array(
					'required' => false,
					'type' => 'LiveAuctionDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocationDefaulted' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ThirdPartyCheckout' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'UseTaxTable' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'GetItFast' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BuyerResponsibleForShipping' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LimitedWarrantyEligible' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayNotes' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'QuestionCount' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Relisted' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'QuantityAvailable' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SKU' =>
				array(
					'required' => false,
					'type' => 'SKUType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CategoryBasedAttributesPrefill' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SearchDetails' =>
				array(
					'required' => false,
					'type' => 'SearchDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PostalCode' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShippingTermsInDescription' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExternalProductID' =>
				array(
					'required' => false,
					'type' => 'ExternalProductIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellerInventoryID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PictureDetails' =>
				array(
					'required' => false,
					'type' => 'PictureDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DigitalDeliveryDetails' =>
				array(
					'required' => false,
					'type' => 'DigitalDeliveryDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DispatchTimeMax' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SkypeEnabled' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SkypeID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SkypeOption' =>
				array(
					'required' => false,
					'type' => 'SkypeOptionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'SkypeContactOption' =>
				array(
					'required' => false,
					'type' => 'SkypeContactOptionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'BestOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalListing' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ThirdPartyCheckoutIntegration' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressOptOut' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingCheckoutRedirectPreference' =>
				array(
					'required' => false,
					'type' => 'ListingCheckoutRedirectPreferenceType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressDetails' =>
				array(
					'required' => false,
					'type' => 'ExpressDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellerContactDetails' =>
				array(
					'required' => false,
					'type' => 'AddressType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TotalQuestionCount' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProxyItem' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
