<?php
// autogenerated file 17.11.2006 13:29
// $Id: ItemTypeFilterCodeType.php,v 1.1.1.1 2006/12/22 14:38:16 gswkaiser Exp $
// $Log: ItemTypeFilterCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:16  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ItemTypeFilterCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AuctionItemsOnly
	var $AuctionItemsOnly = 'AuctionItemsOnly';
	// @var string $FixedPricedItem
	var $FixedPricedItem = 'FixedPricedItem';
	// @var string $AllItems
	var $AllItems = 'AllItems';
	// @var string $StoreInventoryOnly
	var $StoreInventoryOnly = 'StoreInventoryOnly';
	// @var string $FixedPriceExcludeStoreInventory
	var $FixedPriceExcludeStoreInventory = 'FixedPriceExcludeStoreInventory';
	// @var string $ExcludeStoreInventory
	var $ExcludeStoreInventory = 'ExcludeStoreInventory';
	// @var string $AllItemTypes
	var $AllItemTypes = 'AllItemTypes';
	// @var string $AllFixedPriceItemTypes
	var $AllFixedPriceItemTypes = 'AllFixedPriceItemTypes';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $ClassifiedItemsOnly
	var $ClassifiedItemsOnly = 'ClassifiedItemsOnly';
	// end props

/**
 *

 * @return 
 */
	function ItemTypeFilterCodeType()
	{
		$this->EbatNs_FacetType('ItemTypeFilterCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ItemTypeFilterCodeType = new ItemTypeFilterCodeType();

?>
