<?php
// autogenerated file 17.11.2006 13:29
// $Id: LeaveFeedbackResponseType.php,v 1.1.1.1 2006/12/22 14:38:16 gswkaiser Exp $
// $Log: LeaveFeedbackResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:16  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class LeaveFeedbackResponseType extends AbstractResponseType
{
	// start props
	// @var string $FeedbackID
	var $FeedbackID;
	// end props

/**
 *

 * @return string
 */
	function getFeedbackID()
	{
		return $this->FeedbackID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackID($value)
	{
		$this->FeedbackID = $value;
	}
/**
 *

 * @return 
 */
	function LeaveFeedbackResponseType()
	{
		$this->AbstractResponseType('LeaveFeedbackResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FeedbackID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
