<?php
// autogenerated file 17.11.2006 13:29
// $Id: ListingTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:18 gswkaiser Exp $
// $Log: ListingTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:18  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ListingTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Unknown
	var $Unknown = 'Unknown';
	// @var string $Chinese
	var $Chinese = 'Chinese';
	// @var string $Dutch
	var $Dutch = 'Dutch';
	// @var string $Live
	var $Live = 'Live';
	// @var string $Auction
	var $Auction = 'Auction';
	// @var string $AdType
	var $AdType = 'AdType';
	// @var string $StoresFixedPrice
	var $StoresFixedPrice = 'StoresFixedPrice';
	// @var string $PersonalOffer
	var $PersonalOffer = 'PersonalOffer';
	// @var string $FixedPriceItem
	var $FixedPriceItem = 'FixedPriceItem';
	// @var string $Half
	var $Half = 'Half';
	// @var string $LeadGeneration
	var $LeadGeneration = 'LeadGeneration';
	// @var string $Express
	var $Express = 'Express';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ListingTypeCodeType()
	{
		$this->EbatNs_FacetType('ListingTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ListingTypeCodeType = new ListingTypeCodeType();

?>
