<?php
// autogenerated file 17.11.2006 13:29
// $Id: ListingAnalyzerRecommendationsType.php,v 1.1.1.1 2006/12/22 14:38:16 gswkaiser Exp $
// $Log: ListingAnalyzerRecommendationsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:16  gswkaiser
// no message
//
//
require_once 'ListingTipArrayType.php';
require_once 'EbatNs_ComplexType.php';

class ListingAnalyzerRecommendationsType extends EbatNs_ComplexType
{
	// start props
	// @var ListingTipArrayType $ListingTipArray
	var $ListingTipArray;
	// end props

/**
 *

 * @return ListingTipArrayType
 */
	function getListingTipArray()
	{
		return $this->ListingTipArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingTipArray($value)
	{
		$this->ListingTipArray = $value;
	}
/**
 *

 * @return 
 */
	function ListingAnalyzerRecommendationsType()
	{
		$this->EbatNs_ComplexType('ListingAnalyzerRecommendationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ListingTipArray' =>
				array(
					'required' => false,
					'type' => 'ListingTipArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
