<?php
// autogenerated file 17.11.2006 13:29
// $Id: ListingDurationDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:17 gswkaiser Exp $
// $Log: ListingDurationDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:17  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ListingDurationDefinitionType extends EbatNs_ComplexType
{
	// start props
	// @var token $Duration
	var $Duration;
	// end props

/**
 *

 * @return token
 * @param  $index 
 */
	function getDuration($index = null)
	{
		if ($index) {
		return $this->Duration[$index];
	} else {
		return $this->Duration;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setDuration($value, $index = null)
	{
		if ($index) {
	$this->Duration[$index] = $value;
	} else {
	$this->Duration = $value;
	}

	}
/**
 *

 * @return 
 */
	function ListingDurationDefinitionType()
	{
		$this->EbatNs_ComplexType('ListingDurationDefinitionType', 'http://www.w3.org/2001/XMLSchema');
		$this->_elements = array_merge($this->_elements,
			array(
				'Duration' =>
				array(
					'required' => false,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));
	$this->_attributes = array_merge($this->_attributes,
		array(
			'durationSetID' =>
			array(
				'name' => 'durationSetID',
				'type' => 'int',
				'use' => 'required'
			)
		));

	}
}
?>
