<?php
// autogenerated file 17.11.2006 13:29
// $Id: ListingEnhancementsCodeType.php,v 1.1.1.1 2006/12/22 14:38:17 gswkaiser Exp $
// $Log: ListingEnhancementsCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:17  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ListingEnhancementsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Border
	var $Border = 'Border';
	// @var string $BoldTitle
	var $BoldTitle = 'BoldTitle';
	// @var string $Featured
	var $Featured = 'Featured';
	// @var string $Highlight
	var $Highlight = 'Highlight';
	// @var string $HomePageFeatured
	var $HomePageFeatured = 'HomePageFeatured';
	// @var string $ProPackBundle
	var $ProPackBundle = 'ProPackBundle';
	// @var string $BasicUpgradePackBundle
	var $BasicUpgradePackBundle = 'BasicUpgradePackBundle';
	// @var string $ValuePackBundle
	var $ValuePackBundle = 'ValuePackBundle';
	// @var string $ProPackPlusBundle
	var $ProPackPlusBundle = 'ProPackPlusBundle';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ListingEnhancementsCodeType()
	{
		$this->EbatNs_FacetType('ListingEnhancementsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ListingEnhancementsCodeType = new ListingEnhancementsCodeType();

?>
