<?php
// autogenerated file 17.11.2006 13:29
// $Id: LocalListingDistancesSpecialtyDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:19 gswkaiser Exp $
// $Log: LocalListingDistancesSpecialtyDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:19  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class LocalListingDistancesSpecialtyDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function LocalListingDistancesSpecialtyDefinitionType()
	{
		$this->EbatNs_ComplexType('LocalListingDistancesSpecialtyDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
