<?php
// autogenerated file 17.11.2006 13:29
// $Id: MarkUpMarkDownEventTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:19 gswkaiser Exp $
// $Log: MarkUpMarkDownEventTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:19  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class MarkUpMarkDownEventTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $MarkUp
	var $MarkUp = 'MarkUp';
	// @var string $MarkDown
	var $MarkDown = 'MarkDown';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function MarkUpMarkDownEventTypeCodeType()
	{
		$this->EbatNs_FacetType('MarkUpMarkDownEventTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MarkUpMarkDownEventTypeCodeType = new MarkUpMarkDownEventTypeCodeType();

?>
