<?php
// autogenerated file 17.11.2006 13:29
// $Id: MeasureType.php,v 1.1.1.1 2006/12/22 14:38:19 gswkaiser Exp $
// $Log: MeasureType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:19  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class MeasureType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MeasureType()
	{
		$this->EbatNs_ComplexType('MeasureType', 'urn:ebay:apis:eBLBaseComponents');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'unit' =>
			array(
				'name' => 'unit',
				'type' => 'token',
				'use' => 'required'
			),
			'measurementSystem' =>
			array(
				'name' => 'measurementSystem',
				'type' => 'MeasurementSystemCodeType',
				'use' => 'required'
			)
		));

	}
}
?>
