<?php
// autogenerated file 17.11.2006 13:29
// $Id: MemberMessageExchangeArrayType.php,v 1.1.1.1 2006/12/22 14:38:19 gswkaiser Exp $
// $Log: MemberMessageExchangeArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:19  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'MemberMessageExchangeType.php';

class MemberMessageExchangeArrayType extends EbatNs_ComplexType
{
	// start props
	// @var MemberMessageExchangeType $MemberMessageExchange
	var $MemberMessageExchange;
	// end props

/**
 *

 * @return MemberMessageExchangeType
 * @param  $index 
 */
	function getMemberMessageExchange($index = null)
	{
		if ($index) {
		return $this->MemberMessageExchange[$index];
	} else {
		return $this->MemberMessageExchange;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setMemberMessageExchange($value, $index = null)
	{
		if ($index) {
	$this->MemberMessageExchange[$index] = $value;
	} else {
	$this->MemberMessageExchange = $value;
	}

	}
/**
 *

 * @return 
 */
	function MemberMessageExchangeArrayType()
	{
		$this->EbatNs_ComplexType('MemberMessageExchangeArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MemberMessageExchange' =>
				array(
					'required' => false,
					'type' => 'MemberMessageExchangeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
