<?php
// autogenerated file 17.11.2006 13:29
// $Id: MessageStatusTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:20 gswkaiser Exp $
// $Log: MessageStatusTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:20  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class MessageStatusTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Answered
	var $Answered = 'Answered';
	// @var string $Unanswered
	var $Unanswered = 'Unanswered';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function MessageStatusTypeCodeType()
	{
		$this->EbatNs_FacetType('MessageStatusTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MessageStatusTypeCodeType = new MessageStatusTypeCodeType();

?>
