<?php
// autogenerated file 17.11.2006 13:29
// $Id: MinimumReservePriceDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:20 gswkaiser Exp $
// $Log: MinimumReservePriceDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:20  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class MinimumReservePriceDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MinimumReservePriceDefinitionType()
	{
		$this->EbatNs_ComplexType('MinimumReservePriceDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
