<?php
// autogenerated file 17.11.2006 13:29
// $Id: MyMessagesAlertIDType.php,v 1.1.1.1 2006/12/22 14:38:21 gswkaiser Exp $
// $Log: MyMessagesAlertIDType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:21  gswkaiser
// no message
//
//
require_once 'EbatNs_SimpleType.php';

class MyMessagesAlertIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MyMessagesAlertIDType()
	{
		$this->EbatNs_SimpleType('MyMessagesAlertIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesAlertIDType = new MyMessagesAlertIDType();

?>
