<?php
// autogenerated file 17.11.2006 13:29
// $Id: MyMessagesMessageIDType.php,v 1.1.1.1 2006/12/22 14:38:22 gswkaiser Exp $
// $Log: MyMessagesMessageIDType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:22  gswkaiser
// no message
//
//
require_once 'EbatNs_SimpleType.php';

class MyMessagesMessageIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MyMessagesMessageIDType()
	{
		$this->EbatNs_SimpleType('MyMessagesMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesMessageIDType = new MyMessagesMessageIDType();

?>
