<?php
// autogenerated file 17.11.2006 13:29
// $Id: MyMessagesFolderOperationCodeType.php,v 1.1.1.1 2006/12/22 14:38:22 gswkaiser Exp $
// $Log: MyMessagesFolderOperationCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:22  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class MyMessagesFolderOperationCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Display
	var $Display = 'Display';
	// @var string $Rename
	var $Rename = 'Rename';
	// @var string $Remove
	var $Remove = 'Remove';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function MyMessagesFolderOperationCodeType()
	{
		$this->EbatNs_FacetType('MyMessagesFolderOperationCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesFolderOperationCodeType = new MyMessagesFolderOperationCodeType();

?>
