<?php
// autogenerated file 17.11.2006 13:29
// $Id: MyMessagesMessageArrayType.php,v 1.1.1.1 2006/12/22 14:38:22 gswkaiser Exp $
// $Log: MyMessagesMessageArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:22  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'MyMessagesMessageType.php';

class MyMessagesMessageArrayType extends EbatNs_ComplexType
{
	// start props
	// @var MyMessagesMessageType $Message
	var $Message;
	// end props

/**
 *

 * @return MyMessagesMessageType
 * @param  $index 
 */
	function getMessage($index = null)
	{
		if ($index) {
		return $this->Message[$index];
	} else {
		return $this->Message;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setMessage($value, $index = null)
	{
		if ($index) {
	$this->Message[$index] = $value;
	} else {
	$this->Message = $value;
	}

	}
/**
 *

 * @return 
 */
	function MyMessagesMessageArrayType()
	{
		$this->EbatNs_ComplexType('MyMessagesMessageArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Message' =>
				array(
					'required' => false,
					'type' => 'MyMessagesMessageType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
