<?php
// autogenerated file 17.11.2006 13:29
// $Id: MyMessagesMessageIDArrayType.php,v 1.1.1.1 2006/12/22 14:38:22 gswkaiser Exp $
// $Log: MyMessagesMessageIDArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:22  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'MyMessagesMessageIDType.php';

class MyMessagesMessageIDArrayType extends EbatNs_ComplexType
{
	// start props
	// @var MyMessagesMessageIDType $MessageID
	var $MessageID;
	// end props

/**
 *

 * @return MyMessagesMessageIDType
 * @param  $index 
 */
	function getMessageID($index = null)
	{
		if ($index) {
		return $this->MessageID[$index];
	} else {
		return $this->MessageID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setMessageID($value, $index = null)
	{
		if ($index) {
	$this->MessageID[$index] = $value;
	} else {
	$this->MessageID = $value;
	}

	}
/**
 *

 * @return 
 */
	function MyMessagesMessageIDArrayType()
	{
		$this->EbatNs_ComplexType('MyMessagesMessageIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MessageID' =>
				array(
					'required' => false,
					'type' => 'MyMessagesMessageIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
