<?php
// autogenerated file 17.11.2006 13:29
// $Id: NotificationPayloadTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:24 gswkaiser Exp $
// $Log: NotificationPayloadTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:24  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class NotificationPayloadTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $eBLSchemaSOAP
	var $eBLSchemaSOAP = 'eBLSchemaSOAP';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function NotificationPayloadTypeCodeType()
	{
		$this->EbatNs_FacetType('NotificationPayloadTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_NotificationPayloadTypeCodeType = new NotificationPayloadTypeCodeType();

?>
