<?php
// autogenerated file 17.11.2006 13:29
// $Id: OrderArrayType.php,v 1.1.1.1 2006/12/22 14:38:25 gswkaiser Exp $
// $Log: OrderArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:25  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'OrderType.php';

class OrderArrayType extends EbatNs_ComplexType
{
	// start props
	// @var OrderType $Order
	var $Order;
	// end props

/**
 *

 * @return OrderType
 * @param  $index 
 */
	function getOrder($index = null)
	{
		if ($index) {
		return $this->Order[$index];
	} else {
		return $this->Order;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setOrder($value, $index = null)
	{
		if ($index) {
	$this->Order[$index] = $value;
	} else {
	$this->Order = $value;
	}

	}
/**
 *

 * @return 
 */
	function OrderArrayType()
	{
		$this->EbatNs_ComplexType('OrderArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Order' =>
				array(
					'required' => false,
					'type' => 'OrderType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
