<?php
// autogenerated file 17.11.2006 13:29
// $Id: OrderIDType.php,v 1.1.1.1 2006/12/22 14:38:25 gswkaiser Exp $
// $Log: OrderIDType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:25  gswkaiser
// no message
//
//
require_once 'EbatNs_SimpleType.php';

class OrderIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function OrderIDType()
	{
		$this->EbatNs_SimpleType('OrderIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_OrderIDType = new OrderIDType();

?>
