<?php
// autogenerated file 17.11.2006 13:29
// $Id: OrderStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:25 gswkaiser Exp $
// $Log: OrderStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:25  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class OrderStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Active
	var $Active = 'Active';
	// @var string $Inactive
	var $Inactive = 'Inactive';
	// @var string $Completed
	var $Completed = 'Completed';
	// @var string $Cancelled
	var $Cancelled = 'Cancelled';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function OrderStatusCodeType()
	{
		$this->EbatNs_FacetType('OrderStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_OrderStatusCodeType = new OrderStatusCodeType();

?>
