<?php
// autogenerated file 17.11.2006 13:29
// $Id: PaginatedOrderTransactionArrayType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PaginatedOrderTransactionArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'OrderTransactionArrayType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'PaginationResultType.php';

class PaginatedOrderTransactionArrayType extends EbatNs_ComplexType
{
	// start props
	// @var OrderTransactionArrayType $OrderTransactionArray
	var $OrderTransactionArray;
	// @var PaginationResultType $PaginationResult
	var $PaginationResult;
	// end props

/**
 *

 * @return OrderTransactionArrayType
 */
	function getOrderTransactionArray()
	{
		return $this->OrderTransactionArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrderTransactionArray($value)
	{
		$this->OrderTransactionArray = $value;
	}
/**
 *

 * @return PaginationResultType
 */
	function getPaginationResult()
	{
		return $this->PaginationResult;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaginationResult($value)
	{
		$this->PaginationResult = $value;
	}
/**
 *

 * @return 
 */
	function PaginatedOrderTransactionArrayType()
	{
		$this->EbatNs_ComplexType('PaginatedOrderTransactionArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'OrderTransactionArray' =>
				array(
					'required' => false,
					'type' => 'OrderTransactionArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaginationResult' =>
				array(
					'required' => false,
					'type' => 'PaginationResultType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
