<?php
// autogenerated file 17.11.2006 13:29
// $Id: PaginationResultType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PaginationResultType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class PaginationResultType extends EbatNs_ComplexType
{
	// start props
	// @var int $TotalNumberOfPages
	var $TotalNumberOfPages;
	// @var int $TotalNumberOfEntries
	var $TotalNumberOfEntries;
	// end props

/**
 *

 * @return int
 */
	function getTotalNumberOfPages()
	{
		return $this->TotalNumberOfPages;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTotalNumberOfPages($value)
	{
		$this->TotalNumberOfPages = $value;
	}
/**
 *

 * @return int
 */
	function getTotalNumberOfEntries()
	{
		return $this->TotalNumberOfEntries;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTotalNumberOfEntries($value)
	{
		$this->TotalNumberOfEntries = $value;
	}
/**
 *

 * @return 
 */
	function PaginationResultType()
	{
		$this->EbatNs_ComplexType('PaginationResultType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'TotalNumberOfPages' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TotalNumberOfEntries' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
