<?php
// autogenerated file 20.03.2006 20:59
// $Id: PaymentType.php,v 2.0.0 2006/12/14 05:23:29 gswkaiser Exp $
// $Log: PaymentType.php,v $
// Revision 2.0.0  2006/12/14 05:23:29  gswkaiser
// no message
//
// Revision 1.6  2006/03/20 20:19:42  carsten
// *** empty log message ***
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'PaymentMeansType.php';

class PaymentType extends EbatNs_ComplexType
{
	// start props
	// @var PaymentMeansType $PaymentMeans
	var $PaymentMeans;
	// end props

/**
 *

 * @return PaymentMeansType
 */
	function getPaymentMeans()
	{
		return $this->PaymentMeans;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaymentMeans($value)
	{
		$this->PaymentMeans = $value;
	}
/**
 *

 * @return 
 */
	function PaymentType()
	{
		$this->EbatNs_ComplexType('PaymentType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'PaymentMeans' =>
				array(
					'required' => false,
					'type' => 'PaymentMeansType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
