<?php
// autogenerated file 17.11.2006 13:29
// $Id: PaymentTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PaymentTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PaymentTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Sale
	var $Sale = 'Sale';
	// @var string $Refund
	var $Refund = 'Refund';
	// @var string $SellerDeniedPayment
	var $SellerDeniedPayment = 'SellerDeniedPayment';
	// @var string $AdminReversal
	var $AdminReversal = 'AdminReversal';
	// @var string $AllOther
	var $AllOther = 'AllOther';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PaymentTypeCodeType()
	{
		$this->EbatNs_FacetType('PaymentTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PaymentTypeCodeType = new PaymentTypeCodeType();

?>
