<?php
// autogenerated file 17.11.2006 13:29
// $Id: PaymentStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PaymentStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PaymentStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NoPaymentFailure
	var $NoPaymentFailure = 'NoPaymentFailure';
	// @var string $BuyerECheckBounced
	var $BuyerECheckBounced = 'BuyerECheckBounced';
	// @var string $BuyerCreditCardFailed
	var $BuyerCreditCardFailed = 'BuyerCreditCardFailed';
	// @var string $BuyerFailedPaymentReportedBySeller
	var $BuyerFailedPaymentReportedBySeller = 'BuyerFailedPaymentReportedBySeller';
	// @var string $PayPalPaymentInProcess
	var $PayPalPaymentInProcess = 'PayPalPaymentInProcess';
	// @var string $PaymentInProcess
	var $PaymentInProcess = 'PaymentInProcess';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PaymentStatusCodeType()
	{
		$this->EbatNs_FacetType('PaymentStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PaymentStatusCodeType = new PaymentStatusCodeType();

?>
