<?php
// autogenerated file 17.11.2006 13:29
// $Id: PayPalAccountStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PayPalAccountStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PayPalAccountStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Active
	var $Active = 'Active';
	// @var string $Closed
	var $Closed = 'Closed';
	// @var string $HighRestricted
	var $HighRestricted = 'HighRestricted';
	// @var string $LowRestricted
	var $LowRestricted = 'LowRestricted';
	// @var string $Locked
	var $Locked = 'Locked';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $WireOff
	var $WireOff = 'WireOff';
	// @var string $Unknown
	var $Unknown = 'Unknown';
	// @var string $Invalid
	var $Invalid = 'Invalid';
	// end props

/**
 *

 * @return 
 */
	function PayPalAccountStatusCodeType()
	{
		$this->EbatNs_FacetType('PayPalAccountStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PayPalAccountStatusCodeType = new PayPalAccountStatusCodeType();

?>
