<?php
// autogenerated file 17.11.2006 13:29
// $Id: PayPalAccountLevelCodeType.php,v 1.1.1.1 2006/12/22 14:38:26 gswkaiser Exp $
// $Log: PayPalAccountLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:26  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PayPalAccountLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Unverified
	var $Unverified = 'Unverified';
	// @var string $InternationalUnverified
	var $InternationalUnverified = 'InternationalUnverified';
	// @var string $Verified
	var $Verified = 'Verified';
	// @var string $InternationalVerified
	var $InternationalVerified = 'InternationalVerified';
	// @var string $Trusted
	var $Trusted = 'Trusted';
	// @var string $Unknown
	var $Unknown = 'Unknown';
	// @var string $Invalid
	var $Invalid = 'Invalid';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PayPalAccountLevelCodeType()
	{
		$this->EbatNs_FacetType('PayPalAccountLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PayPalAccountLevelCodeType = new PayPalAccountLevelCodeType();

?>
