<?php
// autogenerated file 17.11.2006 13:29
// $Id: PayPalAccountTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:27 gswkaiser Exp $
// $Log: PayPalAccountTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:27  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PayPalAccountTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Personal
	var $Personal = 'Personal';
	// @var string $Premier
	var $Premier = 'Premier';
	// @var string $Business
	var $Business = 'Business';
	// @var string $Unknown
	var $Unknown = 'Unknown';
	// @var string $Invalid
	var $Invalid = 'Invalid';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PayPalAccountTypeCodeType()
	{
		$this->EbatNs_FacetType('PayPalAccountTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PayPalAccountTypeCodeType = new PayPalAccountTypeCodeType();

?>
