<?php
// autogenerated file 17.11.2006 13:29
// $Id: PhotoDisplayCodeType.php,v 1.1.1.1 2006/12/22 14:38:27 gswkaiser Exp $
// $Log: PhotoDisplayCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:27  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PhotoDisplayCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $SlideShow
	var $SlideShow = 'SlideShow';
	// @var string $SuperSize
	var $SuperSize = 'SuperSize';
	// @var string $PicturePack
	var $PicturePack = 'PicturePack';
	// @var string $SiteHostedPictureShow
	var $SiteHostedPictureShow = 'SiteHostedPictureShow';
	// @var string $VendorHostedPictureShow
	var $VendorHostedPictureShow = 'VendorHostedPictureShow';
	// @var string $SuperSizePictureShow
	var $SuperSizePictureShow = 'SuperSizePictureShow';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PhotoDisplayCodeType()
	{
		$this->EbatNs_FacetType('PhotoDisplayCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PhotoDisplayCodeType = new PhotoDisplayCodeType();

?>
