<?php
// autogenerated file 17.11.2006 13:29
// $Id: PictureManagerDetailLevelCodeType.php,v 1.1.1.1 2006/12/22 14:38:27 gswkaiser Exp $
// $Log: PictureManagerDetailLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:27  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PictureManagerDetailLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ReturnAll
	var $ReturnAll = 'ReturnAll';
	// @var string $ReturnSubscription
	var $ReturnSubscription = 'ReturnSubscription';
	// @var string $ReturnPicture
	var $ReturnPicture = 'ReturnPicture';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PictureManagerDetailLevelCodeType()
	{
		$this->EbatNs_FacetType('PictureManagerDetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PictureManagerDetailLevelCodeType = new PictureManagerDetailLevelCodeType();

?>
