<?php
// autogenerated file 17.11.2006 13:29
// $Id: PictureSourceCodeType.php,v 1.1.1.1 2006/12/22 14:38:28 gswkaiser Exp $
// $Log: PictureSourceCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:28  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PictureSourceCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $EPS
	var $EPS = 'EPS';
	// @var string $PictureManager
	var $PictureManager = 'PictureManager';
	// @var string $Vendor
	var $Vendor = 'Vendor';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PictureSourceCodeType()
	{
		$this->EbatNs_FacetType('PictureSourceCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PictureSourceCodeType = new PictureSourceCodeType();

?>
