<?php
// autogenerated file 17.11.2006 13:29
// $Id: PlaceOfferResponseType.php,v 1.1.1.1 2006/12/22 14:38:28 gswkaiser Exp $
// $Log: PlaceOfferResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:28  gswkaiser
// no message
//
//
require_once 'SellingStatusType.php';
require_once 'AbstractResponseType.php';

class PlaceOfferResponseType extends AbstractResponseType
{
	// start props
	// @var SellingStatusType $SellingStatus
	var $SellingStatus;
	// end props

/**
 *

 * @return SellingStatusType
 */
	function getSellingStatus()
	{
		return $this->SellingStatus;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellingStatus($value)
	{
		$this->SellingStatus = $value;
	}
/**
 *

 * @return 
 */
	function PlaceOfferResponseType()
	{
		$this->AbstractResponseType('PlaceOfferResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SellingStatus' =>
				array(
					'required' => false,
					'type' => 'SellingStatusType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
