<?php
// autogenerated file 17.11.2006 13:29
// $Id: PricingRecommendationsType.php,v 1.1.1.1 2006/12/22 14:38:28 gswkaiser Exp $
// $Log: PricingRecommendationsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:28  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ProductInfoType.php';

class PricingRecommendationsType extends EbatNs_ComplexType
{
	// start props
	// @var ProductInfoType $ProductInfo
	var $ProductInfo;
	// end props

/**
 *

 * @return ProductInfoType
 */
	function getProductInfo()
	{
		return $this->ProductInfo;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProductInfo($value)
	{
		$this->ProductInfo = $value;
	}
/**
 *

 * @return 
 */
	function PricingRecommendationsType()
	{
		$this->EbatNs_ComplexType('PricingRecommendationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ProductInfo' =>
				array(
					'required' => false,
					'type' => 'ProductInfoType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
