<?php
// autogenerated file 17.11.2006 13:29
// $Id: ProductUseCaseCodeType.php,v 1.1.1.1 2006/12/22 14:38:30 gswkaiser Exp $
// $Log: ProductUseCaseCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:30  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ProductUseCaseCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AddItem
	var $AddItem = 'AddItem';
	// @var string $ReviseItem
	var $ReviseItem = 'ReviseItem';
	// @var string $RelistItem
	var $RelistItem = 'RelistItem';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ProductUseCaseCodeType()
	{
		$this->EbatNs_FacetType('ProductUseCaseCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ProductUseCaseCodeType = new ProductUseCaseCodeType();

?>
