<?php
// autogenerated file 17.11.2006 13:29
// $Id: ProductSearchResultType.php,v 1.1.1.1.2.1 2007/04/08 07:16:39 gswkaiser Exp $
// $Log: ProductSearchResultType.php,v $
// Revision 1.1.1.1.2.1  2007/04/08 07:16:39  gswkaiser
// olcommerce_2_0_0
//
// Update
//
// Revision 1.1.1.1  2006/12/22 14:38:29  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ProductFinderConstraintType.php';
require_once 'ProductFamilyType.php';
require_once 'ResponseAttributeSetType.php';

class ProductSearchResultType extends EbatNs_ComplexType
{
	// start props
	// @var int $ApproximatePages
	var $ApproximatePages;
	// @var int $AttributeSetID
	var $AttributeSetID;
	// @var boolean $HasMore
	var $HasMore;
	// @var ProductFamilyType $ProductFamilies
	var $ProductFamilies;
	// @var ProductFinderConstraintType $ProductFinderConstraints
	var $ProductFinderConstraints;
	// @var boolean $TooManyMatchesFound
	var $TooManyMatchesFound;
	// @var int $TotalProducts
	var $TotalProducts;
	// @var string $id
	var $id;
	// @var string $NumProducts
	var $NumProducts;
	// @var ResponseAttributeSetType $AttributeSet
	var $AttributeSet;
	// @var boolean $DisplayStockPhotos
	var $DisplayStockPhotos;
	// end props

/**
 *

 * @return int
 */
	function getApproximatePages()
	{
		return $this->ApproximatePages;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setApproximatePages($value)
	{
		$this->ApproximatePages = $value;
	}
/**
 *

 * @return int
 */
	function getAttributeSetID()
	{
		return $this->AttributeSetID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAttributeSetID($value)
	{
		$this->AttributeSetID = $value;
	}
/**
 *

 * @return boolean
 */
	function getHasMore()
	{
		return $this->HasMore;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHasMore($value)
	{
		$this->HasMore = $value;
	}
/**
 *

 * @return ProductFamilyType
 * @param  $index 
 */
	function getProductFamilies($index = null)
	{
		if ($index) {
		return $this->ProductFamilies[$index];
	} else {
		return $this->ProductFamilies;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setProductFamilies($value, $index = null)
	{
		if ($index) {
	$this->ProductFamilies[$index] = $value;
	} else {
	$this->ProductFamilies = $value;
	}

	}
/**
 *

 * @return ProductFinderConstraintType
 * @param  $index 
 */
	function getProductFinderConstraints($index = null)
	{
		if ($index) {
		return $this->ProductFinderConstraints[$index];
	} else {
		return $this->ProductFinderConstraints;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setProductFinderConstraints($value, $index = null)
	{
		if ($index) {
	$this->ProductFinderConstraints[$index] = $value;
	} else {
	$this->ProductFinderConstraints = $value;
	}

	}
/**
 *

 * @return boolean
 */
	function getTooManyMatchesFound()
	{
		return $this->TooManyMatchesFound;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTooManyMatchesFound($value)
	{
		$this->TooManyMatchesFound = $value;
	}
/**
 *

 * @return int
 */
	function getTotalProducts()
	{
		return $this->TotalProducts;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTotalProducts($value)
	{
		$this->TotalProducts = $value;
	}
/**
 *

 * @return string
 */
	function getID()
	{
		return $this->id;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setID($value)
	{
		$this->id = $value;
	}
/**
 *

 * @return string
 */
	function getNumProducts()
	{
		return $this->NumProducts;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setNumProducts($value)
	{
		$this->NumProducts = $value;
	}
/**
 *

 * @return ResponseAttributeSetType
 * @param  $index 
 */
	function getAttributeSet($index = null)
	{
		if ($index) {
		return $this->AttributeSet[$index];
	} else {
		return $this->AttributeSet;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAttributeSet($value, $index = null)
	{
		if ($index) {
	$this->AttributeSet[$index] = $value;
	} else {
	$this->AttributeSet = $value;
	}

	}
/**
 *

 * @return boolean
 */
	function getDisplayStockPhotos()
	{
		return $this->DisplayStockPhotos;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDisplayStockPhotos($value)
	{
		$this->DisplayStockPhotos = $value;
	}
/**
 *

 * @return 
 */
	function ProductSearchResultType()
	{
		$this->EbatNs_ComplexType('ProductSearchResultType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ApproximatePages' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AttributeSetID' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'HasMore' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProductFamilies' =>
				array(
					'required' => false,
					'type' => 'ProductFamilyType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'ProductFinderConstraints' =>
				array(
					'required' => false,
					'type' => 'ProductFinderConstraintType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'TooManyMatchesFound' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TotalProducts' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'id' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'NumProducts' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AttributeSet' =>
				array(
					'required' => false,
					'type' => 'ResponseAttributeSetType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'DisplayStockPhotos' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
