<?php
// autogenerated file 17.11.2006 13:29
// $Id: PromotionMethodCodeType.php,v 1.1.1.1 2006/12/22 14:38:31 gswkaiser Exp $
// $Log: PromotionMethodCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:31  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PromotionMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $CrossSell
	var $CrossSell = 'CrossSell';
	// @var string $UpSell
	var $UpSell = 'UpSell';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PromotionMethodCodeType()
	{
		$this->EbatNs_FacetType('PromotionMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PromotionMethodCodeType = new PromotionMethodCodeType();

?>
