<?php
// autogenerated file 17.11.2006 13:29
// $Id: PromotionItemPriceTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:31 gswkaiser Exp $
// $Log: PromotionItemPriceTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:31  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class PromotionItemPriceTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AuctionPrice
	var $AuctionPrice = 'AuctionPrice';
	// @var string $BuyItNowPrice
	var $BuyItNowPrice = 'BuyItNowPrice';
	// @var string $BestOfferOnlyPrice
	var $BestOfferOnlyPrice = 'BestOfferOnlyPrice';
	// @var string $ClassifiedAdPrice
	var $ClassifiedAdPrice = 'ClassifiedAdPrice';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PromotionItemPriceTypeCodeType()
	{
		$this->EbatNs_FacetType('PromotionItemPriceTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PromotionItemPriceTypeCodeType = new PromotionItemPriceTypeCodeType();

?>
