<?php
// autogenerated file 17.11.2006 13:29
// $Id: ProPackEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:31 gswkaiser Exp $
// $Log: ProPackEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:31  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ProPackEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function ProPackEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('ProPackEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
