<?php
// autogenerated file 17.11.2006 13:29
// $Id: QuantityType.php,v 1.1.1.1 2006/12/22 14:38:32 gswkaiser Exp $
// $Log: QuantityType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:32  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class QuantityType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function QuantityType()
	{
		$this->EbatNs_ComplexType('QuantityType', 'http://www.w3.org/2001/XMLSchema');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'unit' =>
			array(
				'name' => 'unit',
				'type' => 'token',
				'use' => 'required'
			)
		));

	}
}
?>
