<?php
// autogenerated file 17.11.2006 13:29
// $Id: RefundReasonCodeType.php,v 1.1.1.1 2006/12/22 14:38:32 gswkaiser Exp $
// $Log: RefundReasonCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:32  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class RefundReasonCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $CannotShipProduct
	var $CannotShipProduct = 'CannotShipProduct';
	// @var string $WrongItemShipped
	var $WrongItemShipped = 'WrongItemShipped';
	// @var string $ItemBadQuality
	var $ItemBadQuality = 'ItemBadQuality';
	// @var string $ItemDamaged
	var $ItemDamaged = 'ItemDamaged';
	// @var string $BuyerRemorse
	var $BuyerRemorse = 'BuyerRemorse';
	// @var string $Other
	var $Other = 'Other';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function RefundReasonCodeType()
	{
		$this->EbatNs_FacetType('RefundReasonCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundReasonCodeType = new RefundReasonCodeType();

?>
