<?php
// autogenerated file 17.11.2006 13:29
// $Id: RefundTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:32 gswkaiser Exp $
// $Log: RefundTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:32  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class RefundTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Full
	var $Full = 'Full';
	// @var string $FullPlusShipping
	var $FullPlusShipping = 'FullPlusShipping';
	// @var string $CustomOrPartial
	var $CustomOrPartial = 'CustomOrPartial';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function RefundTypeCodeType()
	{
		$this->EbatNs_FacetType('RefundTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundTypeCodeType = new RefundTypeCodeType();

?>
