<?php
// autogenerated file 17.11.2006 13:29
// $Id: ReminderCustomizationType.php,v 1.1.1.1 2006/12/22 14:38:32 gswkaiser Exp $
// $Log: ReminderCustomizationType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:32  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ReminderCustomizationType extends EbatNs_ComplexType
{
	// start props
	// @var int $DurationInDays
	var $DurationInDays;
	// @var boolean $Include
	var $Include;
	// end props

/**
 *

 * @return int
 */
	function getDurationInDays()
	{
		return $this->DurationInDays;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDurationInDays($value)
	{
		$this->DurationInDays = $value;
	}
/**
 *

 * @return boolean
 */
	function getInclude()
	{
		return $this->Include;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setInclude($value)
	{
		$this->Include = $value;
	}
/**
 *

 * @return 
 */
	function ReminderCustomizationType()
	{
		$this->EbatNs_ComplexType('ReminderCustomizationType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'DurationInDays' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Include' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
