<?php
// autogenerated file 17.11.2006 13:29
// $Id: RespondToWantItNowPostResponseType.php,v 1.1.1.1 2006/12/22 14:38:33 gswkaiser Exp $
// $Log: RespondToWantItNowPostResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:33  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class RespondToWantItNowPostResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function RespondToWantItNowPostResponseType()
	{
		$this->AbstractResponseType('RespondToWantItNowPostResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
