<?php
// autogenerated file 17.11.2006 13:29
// $Id: ReviseMyMessagesResponseType.php,v 1.1.1.1 2006/12/22 14:38:35 gswkaiser Exp $
// $Log: ReviseMyMessagesResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:35  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class ReviseMyMessagesResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function ReviseMyMessagesResponseType()
	{
		$this->AbstractResponseType('ReviseMyMessagesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
