<?php
// autogenerated file 17.11.2006 13:29
// $Id: SearchResultItemArrayType.php,v 1.1.1.1 2006/12/22 14:38:36 gswkaiser Exp $
// $Log: SearchResultItemArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:36  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SearchResultItemType.php';

class SearchResultItemArrayType extends EbatNs_ComplexType
{
	// start props
	// @var SearchResultItemType $SearchResultItem
	var $SearchResultItem;
	// end props

/**
 *

 * @return SearchResultItemType
 * @param  $index 
 */
	function getSearchResultItem($index = null)
	{
		if ($index) {
		return $this->SearchResultItem[$index];
	} else {
		return $this->SearchResultItem;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setSearchResultItem($value, $index = null)
	{
		if ($index) {
	$this->SearchResultItem[$index] = $value;
	} else {
	$this->SearchResultItem = $value;
	}

	}
/**
 *

 * @return 
 */
	function SearchResultItemArrayType()
	{
		$this->EbatNs_ComplexType('SearchResultItemArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SearchResultItem' =>
				array(
					'required' => false,
					'type' => 'SearchResultItemType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
