<?php
// autogenerated file 17.11.2006 13:29
// $Id: SelectionModeCodeType.php,v 1.1.1.1 2006/12/22 14:38:37 gswkaiser Exp $
// $Log: SelectionModeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:37  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SelectionModeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Automatic
	var $Automatic = 'Automatic';
	// @var string $Manual
	var $Manual = 'Manual';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SelectionModeCodeType()
	{
		$this->EbatNs_FacetType('SelectionModeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SelectionModeCodeType = new SelectionModeCodeType();

?>
