<?php
// autogenerated file 17.11.2006 13:29
// $Id: SellerLevelCodeType.php,v 1.1.1.1 2006/12/22 14:38:37 gswkaiser Exp $
// $Log: SellerLevelCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:37  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SellerLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Bronze
	var $Bronze = 'Bronze';
	// @var string $Silver
	var $Silver = 'Silver';
	// @var string $Gold
	var $Gold = 'Gold';
	// @var string $Platinum
	var $Platinum = 'Platinum';
	// @var string $Titanium
	var $Titanium = 'Titanium';
	// @var string $None
	var $None = 'None';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellerLevelCodeType()
	{
		$this->EbatNs_FacetType('SellerLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerLevelCodeType = new SellerLevelCodeType();

?>
