<?php
// autogenerated file 17.11.2006 13:29
// $Id: SellerReverseDisputeResponseType.php,v 1.1.1.1 2006/12/22 14:38:38 gswkaiser Exp $
// $Log: SellerReverseDisputeResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:38  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class SellerReverseDisputeResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SellerReverseDisputeResponseType()
	{
		$this->AbstractResponseType('SellerReverseDisputeResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
