<?php
// autogenerated file 17.11.2006 13:29
// $Id: SellerPaymentMethodCodeType.php,v 1.1.1.1 2006/12/22 14:38:37 gswkaiser Exp $
// $Log: SellerPaymentMethodCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:37  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SellerPaymentMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NothingOnFile
	var $NothingOnFile = 'NothingOnFile';
	// @var string $CreditCard
	var $CreditCard = 'CreditCard';
	// @var string $DirectDebit
	var $DirectDebit = 'DirectDebit';
	// @var string $DirectDebitPendingSignatureMandate
	var $DirectDebitPendingSignatureMandate = 'DirectDebitPendingSignatureMandate';
	// @var string $eBayDirectPay
	var $eBayDirectPay = 'eBayDirectPay';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellerPaymentMethodCodeType()
	{
		$this->EbatNs_FacetType('SellerPaymentMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerPaymentMethodCodeType = new SellerPaymentMethodCodeType();

?>
