<?php
// autogenerated file 17.11.2006 13:29
// $Id: SellerContactDetailsEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:37 gswkaiser Exp $
// $Log: SellerContactDetailsEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:37  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class SellerContactDetailsEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SellerContactDetailsEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('SellerContactDetailsEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
