<?php
// autogenerated file 17.11.2006 13:29
// $Id: SendInvoiceResponseType.php,v 1.1.1.1 2006/12/22 14:38:39 gswkaiser Exp $
// $Log: SendInvoiceResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:39  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class SendInvoiceResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SendInvoiceResponseType()
	{
		$this->AbstractResponseType('SendInvoiceResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
