<?php
// autogenerated file 17.11.2006 13:29
// $Id: SetPromotionRulesResponseType.php,v 1.1.1.1 2006/12/22 14:38:40 gswkaiser Exp $
// $Log: SetPromotionRulesResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:40  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class SetPromotionRulesResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SetPromotionRulesResponseType()
	{
		$this->AbstractResponseType('SetPromotionRulesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
