<?php
// autogenerated file 17.11.2006 13:29
// $Id: SetStoreCategoriesRequestType.php,v 1.1.1.1 2006/12/22 14:38:40 gswkaiser Exp $
// $Log: SetStoreCategoriesRequestType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:40  gswkaiser
// no message
//
//
require_once 'StoreCategoryUpdateActionCodeType.php';
require_once 'StoreCustomCategoryArrayType.php';
require_once 'AbstractRequestType.php';

class SetStoreCategoriesRequestType extends AbstractRequestType
{
	// start props
	// @var StoreCategoryUpdateActionCodeType $Action
	var $Action;
	// @var int $ItemDestinationCategoryID
	var $ItemDestinationCategoryID;
	// @var int $DestinationParentCategoryID
	var $DestinationParentCategoryID;
	// @var StoreCustomCategoryArrayType $StoreCategories
	var $StoreCategories;
	// end props

/**
 *

 * @return StoreCategoryUpdateActionCodeType
 */
	function getAction()
	{
		return $this->Action;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAction($value)
	{
		$this->Action = $value;
	}
/**
 *

 * @return int
 */
	function getItemDestinationCategoryID()
	{
		return $this->ItemDestinationCategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemDestinationCategoryID($value)
	{
		$this->ItemDestinationCategoryID = $value;
	}
/**
 *

 * @return int
 */
	function getDestinationParentCategoryID()
	{
		return $this->DestinationParentCategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDestinationParentCategoryID($value)
	{
		$this->DestinationParentCategoryID = $value;
	}
/**
 *

 * @return StoreCustomCategoryArrayType
 */
	function getStoreCategories()
	{
		return $this->StoreCategories;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoreCategories($value)
	{
		$this->StoreCategories = $value;
	}
/**
 *

 * @return 
 */
	function SetStoreCategoriesRequestType()
	{
		$this->AbstractRequestType('SetStoreCategoriesRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Action' =>
				array(
					'required' => false,
					'type' => 'StoreCategoryUpdateActionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ItemDestinationCategoryID' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DestinationParentCategoryID' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoreCategories' =>
				array(
					'required' => false,
					'type' => 'StoreCustomCategoryArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
