<?php
// autogenerated file 17.11.2006 13:29
// $Id: SetUserPreferencesResponseType.php,v 1.1.1.1 2006/12/22 14:38:41 gswkaiser Exp $
// $Log: SetUserPreferencesResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:41  gswkaiser
// no message
//
//
require_once 'AbstractResponseType.php';

class SetUserPreferencesResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SetUserPreferencesResponseType()
	{
		$this->AbstractResponseType('SetUserPreferencesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
