<?php
// autogenerated file 17.11.2006 13:29
// $Id: SetUserNotesActionCodeType.php,v 1.1.1.1 2006/12/22 14:38:40 gswkaiser Exp $
// $Log: SetUserNotesActionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:40  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SetUserNotesActionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AddOrUpdate
	var $AddOrUpdate = 'AddOrUpdate';
	// @var string $Delete
	var $Delete = 'Delete';
	// end props

/**
 *

 * @return 
 */
	function SetUserNotesActionCodeType()
	{
		$this->EbatNs_FacetType('SetUserNotesActionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SetUserNotesActionCodeType = new SetUserNotesActionCodeType();

?>
