<?php
// autogenerated file 17.11.2006 13:29
// $Id: ShippingFeatureCodeType.php,v 1.1.1.1 2006/12/22 14:38:43 gswkaiser Exp $
// $Log: ShippingFeatureCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:43  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ShippingFeatureCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $DeliveryConfirmation
	var $DeliveryConfirmation = 'DeliveryConfirmation';
	// @var string $SignatureConfirmation
	var $SignatureConfirmation = 'SignatureConfirmation';
	// @var string $StealthPostage
	var $StealthPostage = 'StealthPostage';
	// @var string $SaturdayDelivery
	var $SaturdayDelivery = 'SaturdayDelivery';
	// @var string $Other
	var $Other = 'Other';
	// @var string $NotDefined
	var $NotDefined = 'NotDefined';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ShippingFeatureCodeType()
	{
		$this->EbatNs_FacetType('ShippingFeatureCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShippingFeatureCodeType = new ShippingFeatureCodeType();

?>
