<?php
// autogenerated file 17.11.2006 13:29
// $Id: ShipmentStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:41 gswkaiser Exp $
// $Log: ShipmentStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:41  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ShipmentStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Active
	var $Active = 'Active';
	// @var string $Canceled
	var $Canceled = 'Canceled';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ShipmentStatusCodeType()
	{
		$this->EbatNs_FacetType('ShipmentStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShipmentStatusCodeType = new ShipmentStatusCodeType();

?>
