<?php
// autogenerated file 17.11.2006 13:29
// $Id: ShippingRateTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:43 gswkaiser Exp $
// $Log: ShippingRateTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:43  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class ShippingRateTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $OnDemand
	var $OnDemand = 'OnDemand';
	// @var string $DailyPickup
	var $DailyPickup = 'DailyPickup';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ShippingRateTypeCodeType()
	{
		$this->EbatNs_FacetType('ShippingRateTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShippingRateTypeCodeType = new ShippingRateTypeCodeType();

?>
