<?php
// autogenerated file 17.11.2006 13:29
// $Id: ShippingTermRequiredDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:46 gswkaiser Exp $
// $Log: ShippingTermRequiredDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:46  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class ShippingTermRequiredDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function ShippingTermRequiredDefinitionType()
	{
		$this->EbatNs_ComplexType('ShippingTermRequiredDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
