<?php
// autogenerated file 17.11.2006 13:29
// $Id: SIFFTASRecommendationsType.php,v 1.1.1.1 2006/12/22 14:38:46 gswkaiser Exp $
// $Log: SIFFTASRecommendationsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:46  gswkaiser
// no message
//
//
require_once 'AttributeSetArrayType.php';
require_once 'EbatNs_ComplexType.php';

class SIFFTASRecommendationsType extends EbatNs_ComplexType
{
	// start props
	// @var AttributeSetArrayType $AttributeSetArray
	var $AttributeSetArray;
	// end props

/**
 *

 * @return AttributeSetArrayType
 */
	function getAttributeSetArray()
	{
		return $this->AttributeSetArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAttributeSetArray($value)
	{
		$this->AttributeSetArray = $value;
	}
/**
 *

 * @return 
 */
	function SIFFTASRecommendationsType()
	{
		$this->EbatNs_ComplexType('SIFFTASRecommendationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AttributeSetArray' =>
				array(
					'required' => false,
					'type' => 'AttributeSetArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
