<?php
// autogenerated file 17.11.2006 13:29
// $Id: SiteWideCharacteristicsType.php,v 1.1.1.1 2006/12/22 14:38:47 gswkaiser Exp $
// $Log: SiteWideCharacteristicsType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:47  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'CharacteristicsSetType.php';

class SiteWideCharacteristicsType extends EbatNs_ComplexType
{
	// start props
	// @var CharacteristicsSetType $CharacteristicsSet
	var $CharacteristicsSet;
	// @var string $ExcludeCategoryID
	var $ExcludeCategoryID;
	// end props

/**
 *

 * @return CharacteristicsSetType
 */
	function getCharacteristicsSet()
	{
		return $this->CharacteristicsSet;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCharacteristicsSet($value)
	{
		$this->CharacteristicsSet = $value;
	}
/**
 *

 * @return string
 * @param  $index 
 */
	function getExcludeCategoryID($index = null)
	{
		if ($index) {
		return $this->ExcludeCategoryID[$index];
	} else {
		return $this->ExcludeCategoryID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setExcludeCategoryID($value, $index = null)
	{
		if ($index) {
	$this->ExcludeCategoryID[$index] = $value;
	} else {
	$this->ExcludeCategoryID = $value;
	}

	}
/**
 *

 * @return 
 */
	function SiteWideCharacteristicsType()
	{
		$this->EbatNs_ComplexType('SiteWideCharacteristicsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CharacteristicsSet' =>
				array(
					'required' => false,
					'type' => 'CharacteristicsSetType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExcludeCategoryID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
