<?php
// autogenerated file 17.11.2006 13:29
// $Id: SiteLocationType.php,v 1.1.1.1 2006/12/22 14:38:47 gswkaiser Exp $
// $Log: SiteLocationType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:47  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SiteIDFilterCodeType.php';

class SiteLocationType extends EbatNs_ComplexType
{
	// start props
	// @var SiteIDFilterCodeType $SiteID
	var $SiteID;
	// end props

/**
 *

 * @return SiteIDFilterCodeType
 */
	function getSiteID()
	{
		return $this->SiteID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSiteID($value)
	{
		$this->SiteID = $value;
	}
/**
 *

 * @return 
 */
	function SiteLocationType()
	{
		$this->EbatNs_ComplexType('SiteLocationType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SiteID' =>
				array(
					'required' => false,
					'type' => 'SiteIDFilterCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
