<?php
// autogenerated file 17.11.2006 13:29
// $Id: SiteCodeType.php,v 1.1.1.1 2006/12/22 14:38:46 gswkaiser Exp $
// $Log: SiteCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:46  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SiteCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $US
	var $US = 'US';
	// @var string $Canada
	var $Canada = 'Canada';
	// @var string $UK
	var $UK = 'UK';
	// @var string $Australia
	var $Australia = 'Australia';
	// @var string $Austria
	var $Austria = 'Austria';
	// @var string $Belgium_French
	var $Belgium_French = 'Belgium_French';
	// @var string $France
	var $France = 'France';
	// @var string $Germany
	var $Germany = 'Germany';
	// @var string $Italy
	var $Italy = 'Italy';
	// @var string $Belgium_Dutch
	var $Belgium_Dutch = 'Belgium_Dutch';
	// @var string $Netherlands
	var $Netherlands = 'Netherlands';
	// @var string $Spain
	var $Spain = 'Spain';
	// @var string $Switzerland
	var $Switzerland = 'Switzerland';
	// @var string $Taiwan
	var $Taiwan = 'Taiwan';
	// @var string $eBayMotors
	var $eBayMotors = 'eBayMotors';
	// @var string $HongKong
	var $HongKong = 'HongKong';
	// @var string $Singapore
	var $Singapore = 'Singapore';
	// @var string $India
	var $India = 'India';
	// @var string $China
	var $China = 'China';
	// @var string $Ireland
	var $Ireland = 'Ireland';
	// @var string $Malaysia
	var $Malaysia = 'Malaysia';
	// @var string $Philippines
	var $Philippines = 'Philippines';
	// @var string $Poland
	var $Poland = 'Poland';
	// @var string $Sweden
	var $Sweden = 'Sweden';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $CanadaFrench
	var $CanadaFrench = 'CanadaFrench';
	// end props

/**
 *

 * @return 
 */
	function SiteCodeType()
	{
		$this->EbatNs_FacetType('SiteCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SiteCodeType = new SiteCodeType();

?>
