<?php
// autogenerated file 17.11.2006 13:29
// $Id: SkypeContactOptionCodeType.php,v 1.1.1.1 2006/12/22 14:38:48 gswkaiser Exp $
// $Log: SkypeContactOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:48  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class SkypeContactOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Chat
	var $Chat = 'Chat';
	// @var string $Voice
	var $Voice = 'Voice';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SkypeContactOptionCodeType()
	{
		$this->EbatNs_FacetType('SkypeContactOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SkypeContactOptionCodeType = new SkypeContactOptionCodeType();

?>
