<?php
// autogenerated file 17.11.2006 13:29
// $Id: SkypeMeTransactionalEnabledDefinitionType.php,v 1.1.1.1 2006/12/22 14:38:48 gswkaiser Exp $
// $Log: SkypeMeTransactionalEnabledDefinitionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:48  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class SkypeMeTransactionalEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SkypeMeTransactionalEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('SkypeMeTransactionalEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
