<?php
// autogenerated file 17.11.2006 13:29
// $Id: SpellingSuggestionType.php,v 1.1.1.1 2006/12/22 14:38:48 gswkaiser Exp $
// $Log: SpellingSuggestionType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:48  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class SpellingSuggestionType extends EbatNs_ComplexType
{
	// start props
	// @var int $MatchingItemCount
	var $MatchingItemCount;
	// @var string $Text
	var $Text;
	// end props

/**
 *

 * @return int
 */
	function getMatchingItemCount()
	{
		return $this->MatchingItemCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMatchingItemCount($value)
	{
		$this->MatchingItemCount = $value;
	}
/**
 *

 * @return string
 * @param  $index 
 */
	function getText($index = null)
	{
		if ($index) {
		return $this->Text[$index];
	} else {
		return $this->Text;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setText($value, $index = null)
	{
		if ($index) {
	$this->Text[$index] = $value;
	} else {
	$this->Text = $value;
	}

	}
/**
 *

 * @return 
 */
	function SpellingSuggestionType()
	{
		$this->EbatNs_ComplexType('SpellingSuggestionType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MatchingItemCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Text' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
