<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreCustomCategoryType.php,v 1.1.1.1 2006/12/22 14:38:49 gswkaiser Exp $
// $Log: StoreCustomCategoryType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:49  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'StoreCustomCategoryType.php';

class StoreCustomCategoryType extends EbatNs_ComplexType
{
	// start props
	// @var int $CategoryID
	var $CategoryID;
	// @var string $Name
	var $Name;
	// @var int $Order
	var $Order;
	// @var StoreCustomCategoryType $ChildrenCategories
	var $ChildrenCategories;
	// @var StoreCustomCategoryType $ChildCategory
	var $ChildCategory;
	// end props

/**
 *

 * @return int
 */
	function getCategoryID()
	{
		return $this->CategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryID($value)
	{
		$this->CategoryID = $value;
	}
/**
 *

 * @return string
 */
	function getName()
	{
		return $this->Name;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setName($value)
	{
		$this->Name = $value;
	}
/**
 *

 * @return int
 */
	function getOrder()
	{
		return $this->Order;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrder($value)
	{
		$this->Order = $value;
	}
/**
 *

 * @return StoreCustomCategoryType
 */
	function getChildrenCategories()
	{
		return $this->ChildrenCategories;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setChildrenCategories($value)
	{
		$this->ChildrenCategories = $value;
	}
/**
 *

 * @return StoreCustomCategoryType
 * @param  $index 
 */
	function getChildCategory($index = null)
	{
		if ($index) {
		return $this->ChildCategory[$index];
	} else {
		return $this->ChildCategory;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setChildCategory($value, $index = null)
	{
		if ($index) {
	$this->ChildCategory[$index] = $value;
	} else {
	$this->ChildCategory = $value;
	}

	}
/**
 *

 * @return 
 */
	function StoreCustomCategoryType()
	{
		$this->EbatNs_ComplexType('StoreCustomCategoryType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CategoryID' =>
				array(
					'required' => true,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				),
				'Name' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Order' =>
				array(
					'required' => true,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				),
				'ChildrenCategories' =>
				array(
					'required' => false,
					'type' => 'StoreCustomCategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ChildCategory' =>
				array(
					'required' => false,
					'type' => 'StoreCustomCategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
