<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreItemListLayoutCodeType.php,v 1.1.1.1 2006/12/22 14:38:50 gswkaiser Exp $
// $Log: StoreItemListLayoutCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:50  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class StoreItemListLayoutCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ListView
	var $ListView = 'ListView';
	// @var string $GalleryView
	var $GalleryView = 'GalleryView';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function StoreItemListLayoutCodeType()
	{
		$this->EbatNs_FacetType('StoreItemListLayoutCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_StoreItemListLayoutCodeType = new StoreItemListLayoutCodeType();

?>
