<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreColorSchemeArrayType.php,v 1.1.1.1 2006/12/22 14:38:48 gswkaiser Exp $
// $Log: StoreColorSchemeArrayType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:48  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'StoreColorSchemeType.php';

class StoreColorSchemeArrayType extends EbatNs_ComplexType
{
	// start props
	// @var StoreColorSchemeType $ColorScheme
	var $ColorScheme;
	// end props

/**
 *

 * @return StoreColorSchemeType
 * @param  $index 
 */
	function getColorScheme($index = null)
	{
		if ($index) {
		return $this->ColorScheme[$index];
	} else {
		return $this->ColorScheme;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setColorScheme($value, $index = null)
	{
		if ($index) {
	$this->ColorScheme[$index] = $value;
	} else {
	$this->ColorScheme = $value;
	}

	}
/**
 *

 * @return 
 */
	function StoreColorSchemeArrayType()
	{
		$this->EbatNs_ComplexType('StoreColorSchemeArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ColorScheme' =>
				array(
					'required' => false,
					'type' => 'StoreColorSchemeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
