<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreCustomListingHeaderLinkType.php,v 1.1.1.1 2006/12/22 14:38:49 gswkaiser Exp $
// $Log: StoreCustomListingHeaderLinkType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:49  gswkaiser
// no message
//
//
require_once 'StoreCustomListingHeaderLinkCodeType.php';
require_once 'EbatNs_ComplexType.php';

class StoreCustomListingHeaderLinkType extends EbatNs_ComplexType
{
	// start props
	// @var int $LinkID
	var $LinkID;
	// @var int $Order
	var $Order;
	// @var StoreCustomListingHeaderLinkCodeType $LinkType
	var $LinkType;
	// end props

/**
 *

 * @return int
 */
	function getLinkID()
	{
		return $this->LinkID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLinkID($value)
	{
		$this->LinkID = $value;
	}
/**
 *

 * @return int
 */
	function getOrder()
	{
		return $this->Order;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setOrder($value)
	{
		$this->Order = $value;
	}
/**
 *

 * @return StoreCustomListingHeaderLinkCodeType
 */
	function getLinkType()
	{
		return $this->LinkType;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLinkType($value)
	{
		$this->LinkType = $value;
	}
/**
 *

 * @return 
 */
	function StoreCustomListingHeaderLinkType()
	{
		$this->EbatNs_ComplexType('StoreCustomListingHeaderLinkType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'LinkID' =>
				array(
					'required' => true,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				),
				'Order' =>
				array(
					'required' => true,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '1..1'
				),
				'LinkType' =>
				array(
					'required' => false,
					'type' => 'StoreCustomListingHeaderLinkCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
