<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreCustomListingHeaderLinkCodeType.php,v 1.1.1.1 2006/12/22 14:38:49 gswkaiser Exp $
// $Log: StoreCustomListingHeaderLinkCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:49  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class StoreCustomListingHeaderLinkCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $AboutMePage
	var $AboutMePage = 'AboutMePage';
	// @var string $CustomPage
	var $CustomPage = 'CustomPage';
	// @var string $CustomCategory
	var $CustomCategory = 'CustomCategory';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function StoreCustomListingHeaderLinkCodeType()
	{
		$this->EbatNs_FacetType('StoreCustomListingHeaderLinkCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_StoreCustomListingHeaderLinkCodeType = new StoreCustomListingHeaderLinkCodeType();

?>
