<?php
// autogenerated file 17.11.2006 13:29
// $Id: StoreFontSizeCodeType.php,v 1.1.1.1 2006/12/22 14:38:49 gswkaiser Exp $
// $Log: StoreFontSizeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:49  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class StoreFontSizeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $XXS
	var $XXS = 'XXS';
	// @var string $XS
	var $XS = 'XS';
	// @var string $S
	var $S = 'S';
	// @var string $M
	var $M = 'M';
	// @var string $L
	var $L = 'L';
	// @var string $XL
	var $XL = 'XL';
	// @var string $XXL
	var $XXL = 'XXL';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function StoreFontSizeCodeType()
	{
		$this->EbatNs_FacetType('StoreFontSizeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_StoreFontSizeCodeType = new StoreFontSizeCodeType();

?>
