<?php
// autogenerated file 17.11.2006 13:29
// $Id: SummaryEventScheduleType.php,v 1.1.1.1 2006/12/22 14:38:52 gswkaiser Exp $
// $Log: SummaryEventScheduleType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:52  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'NotificationEventTypeCodeType.php';
require_once 'SummaryFrequencyCodeType.php';
require_once 'SummaryWindowPeriodCodeType.php';

class SummaryEventScheduleType extends EbatNs_ComplexType
{
	// start props
	// @var NotificationEventTypeCodeType $EventType
	var $EventType;
	// @var SummaryWindowPeriodCodeType $SummaryPeriod
	var $SummaryPeriod;
	// @var SummaryFrequencyCodeType $Frequency
	var $Frequency;
	// end props

/**
 *

 * @return NotificationEventTypeCodeType
 */
	function getEventType()
	{
		return $this->EventType;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEventType($value)
	{
		$this->EventType = $value;
	}
/**
 *

 * @return SummaryWindowPeriodCodeType
 */
	function getSummaryPeriod()
	{
		return $this->SummaryPeriod;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSummaryPeriod($value)
	{
		$this->SummaryPeriod = $value;
	}
/**
 *

 * @return SummaryFrequencyCodeType
 */
	function getFrequency()
	{
		return $this->Frequency;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFrequency($value)
	{
		$this->Frequency = $value;
	}
/**
 *

 * @return 
 */
	function SummaryEventScheduleType()
	{
		$this->EbatNs_ComplexType('SummaryEventScheduleType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'EventType' =>
				array(
					'required' => false,
					'type' => 'NotificationEventTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SummaryPeriod' =>
				array(
					'required' => false,
					'type' => 'SummaryWindowPeriodCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Frequency' =>
				array(
					'required' => false,
					'type' => 'SummaryFrequencyCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
