<?php
// autogenerated file 17.11.2006 13:30
// $Id: TaskStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:52 gswkaiser Exp $
// $Log: TaskStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:52  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class TaskStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Pending
	var $Pending = 'Pending';
	// @var string $InProgress
	var $InProgress = 'InProgress';
	// @var string $Complete
	var $Complete = 'Complete';
	// @var string $Failed
	var $Failed = 'Failed';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function TaskStatusCodeType()
	{
		$this->EbatNs_FacetType('TaskStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TaskStatusCodeType = new TaskStatusCodeType();

?>
