<?php
// autogenerated file 17.11.2006 13:30
// $Id: TaxTableType.php,v 1.1.1.1 2006/12/22 14:38:52 gswkaiser Exp $
// $Log: TaxTableType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:52  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'TaxJurisdictionType.php';

class TaxTableType extends EbatNs_ComplexType
{
	// start props
	// @var TaxJurisdictionType $TaxJurisdiction
	var $TaxJurisdiction;
	// end props

/**
 *

 * @return TaxJurisdictionType
 * @param  $index 
 */
	function getTaxJurisdiction($index = null)
	{
		if ($index) {
		return $this->TaxJurisdiction[$index];
	} else {
		return $this->TaxJurisdiction;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setTaxJurisdiction($value, $index = null)
	{
		if ($index) {
	$this->TaxJurisdiction[$index] = $value;
	} else {
	$this->TaxJurisdiction = $value;
	}

	}
/**
 *

 * @return 
 */
	function TaxTableType()
	{
		$this->EbatNs_ComplexType('TaxTableType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'TaxJurisdiction' =>
				array(
					'required' => false,
					'type' => 'TaxJurisdictionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
