<?php
// autogenerated file 17.11.2006 13:30
// $Id: TokenReturnMethodCodeType.php,v 1.1.1.1 2006/12/22 14:38:52 gswkaiser Exp $
// $Log: TokenReturnMethodCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:52  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class TokenReturnMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Redirect
	var $Redirect = 'Redirect';
	// @var string $FetchToken
	var $FetchToken = 'FetchToken';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function TokenReturnMethodCodeType()
	{
		$this->EbatNs_FacetType('TokenReturnMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TokenReturnMethodCodeType = new TokenReturnMethodCodeType();

?>
