<?php
// autogenerated file 17.11.2006 13:30
// $Id: TradingRoleCodeType.php,v 1.1.1.1 2006/12/22 14:38:52 gswkaiser Exp $
// $Log: TradingRoleCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:52  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class TradingRoleCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Buyer
	var $Buyer = 'Buyer';
	// @var string $Seller
	var $Seller = 'Seller';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function TradingRoleCodeType()
	{
		$this->EbatNs_FacetType('TradingRoleCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TradingRoleCodeType = new TradingRoleCodeType();

?>
