<?php
// autogenerated file 17.11.2006 13:30
// $Id: TransactionPlatformType.php,v 1.1.1.1 2006/12/22 14:38:53 gswkaiser Exp $
// $Log: TransactionPlatformType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:53  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class TransactionPlatformType extends EbatNs_FacetType
{
	// start props
	// @var string $eBay
	var $eBay = 'eBay';
	// @var string $Express
	var $Express = 'Express';
	// end props

/**
 *

 * @return 
 */
	function TransactionPlatformType()
	{
		$this->EbatNs_FacetType('TransactionPlatformType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TransactionPlatformType = new TransactionPlatformType();

?>
