<?php
// autogenerated file 17.11.2006 13:30
// $Id: UPSRateOptionCodeType.php,v 1.1.1.1 2006/12/22 14:38:54 gswkaiser Exp $
// $Log: UPSRateOptionCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:54  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class UPSRateOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $UPSDailyRates
	var $UPSDailyRates = 'UPSDailyRates';
	// @var string $UPSOnDemandRates
	var $UPSOnDemandRates = 'UPSOnDemandRates';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function UPSRateOptionCodeType()
	{
		$this->EbatNs_FacetType('UPSRateOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_UPSRateOptionCodeType = new UPSRateOptionCodeType();

?>
