<?php
// autogenerated file 17.11.2006 13:30
// $Id: URLTypeCodeType.php,v 1.1.1.1 2006/12/22 14:38:54 gswkaiser Exp $
// $Log: URLTypeCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:54  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class URLTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ViewItemURL
	var $ViewItemURL = 'ViewItemURL';
	// @var string $ViewUserURL
	var $ViewUserURL = 'ViewUserURL';
	// @var string $MyeBayURL
	var $MyeBayURL = 'MyeBayURL';
	// @var string $MyeBayBiddingURL
	var $MyeBayBiddingURL = 'MyeBayBiddingURL';
	// @var string $MyeBayNotWonURL
	var $MyeBayNotWonURL = 'MyeBayNotWonURL';
	// @var string $MyeBayWonURL
	var $MyeBayWonURL = 'MyeBayWonURL';
	// @var string $MyeBayWatchingURL
	var $MyeBayWatchingURL = 'MyeBayWatchingURL';
	// @var string $eBayStoreURL
	var $eBayStoreURL = 'eBayStoreURL';
	// @var string $SmallLogoURL
	var $SmallLogoURL = 'SmallLogoURL';
	// @var string $MediumLogoURL
	var $MediumLogoURL = 'MediumLogoURL';
	// @var string $LargeLogoURL
	var $LargeLogoURL = 'LargeLogoURL';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function URLTypeCodeType()
	{
		$this->EbatNs_FacetType('URLTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_URLTypeCodeType = new URLTypeCodeType();

?>
