<?php
// autogenerated file 17.11.2006 13:30
// $Id: VATStatusCodeType.php,v 1.1.1.1 2006/12/22 14:38:56 gswkaiser Exp $
// $Log: VATStatusCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:56  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class VATStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NoVATTax
	var $NoVATTax = 'NoVATTax';
	// @var string $VATTax
	var $VATTax = 'VATTax';
	// @var string $VATExempt
	var $VATExempt = 'VATExempt';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function VATStatusCodeType()
	{
		$this->EbatNs_FacetType('VATStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_VATStatusCodeType = new VATStatusCodeType();

?>
