<?php
// autogenerated file 17.11.2006 13:29
// $Id: VerifyAddSecondChanceItemResponseType.php,v 1.1.1.1 2006/12/22 14:38:57 gswkaiser Exp $
// $Log: VerifyAddSecondChanceItemResponseType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:57  gswkaiser
// no message
//
//
require_once 'FeesType.php';
require_once 'AbstractResponseType.php';

class VerifyAddSecondChanceItemResponseType extends AbstractResponseType
{
	// start props
	// @var FeesType $Fees
	var $Fees;
	// @var dateTime $StartTime
	var $StartTime;
	// @var dateTime $EndTime
	var $EndTime;
	// end props

/**
 *

 * @return FeesType
 */
	function getFees()
	{
		return $this->Fees;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFees($value)
	{
		$this->Fees = $value;
	}
/**
 *

 * @return dateTime
 */
	function getStartTime()
	{
		return $this->StartTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStartTime($value)
	{
		$this->StartTime = $value;
	}
/**
 *

 * @return dateTime
 */
	function getEndTime()
	{
		return $this->EndTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEndTime($value)
	{
		$this->EndTime = $value;
	}
/**
 *

 * @return 
 */
	function VerifyAddSecondChanceItemResponseType()
	{
		$this->AbstractResponseType('VerifyAddSecondChanceItemResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Fees' =>
				array(
					'required' => false,
					'type' => 'FeesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StartTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EndTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
