<?php
// autogenerated file 17.11.2006 13:30
// $Id: WirelessCarrierIDCodeType.php,v 1.1.1.1 2006/12/22 14:38:58 gswkaiser Exp $
// $Log: WirelessCarrierIDCodeType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:58  gswkaiser
// no message
//
//
require_once 'EbatNs_FacetType.php';

class WirelessCarrierIDCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Cingular
	var $Cingular = 'Cingular';
	// @var string $TMobile
	var $TMobile = 'TMobile';
	// @var string $Sprint
	var $Sprint = 'Sprint';
	// @var string $Nextel
	var $Nextel = 'Nextel';
	// @var string $Verizon
	var $Verizon = 'Verizon';
	// @var string $CincinnatiBell
	var $CincinnatiBell = 'CincinnatiBell';
	// @var string $Dobson
	var $Dobson = 'Dobson';
	// @var string $Alltel
	var $Alltel = 'Alltel';
	// @var string $Leap
	var $Leap = 'Leap';
	// @var string $USCellular
	var $USCellular = 'USCellular';
	// @var string $Movistar
	var $Movistar = 'Movistar';
	// @var string $Amena
	var $Amena = 'Amena';
	// @var string $Vodafone
	var $Vodafone = 'Vodafone';
	// @var string $ATT
	var $ATT = 'ATT';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function WirelessCarrierIDCodeType()
	{
		$this->EbatNs_FacetType('WirelessCarrierIDCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_WirelessCarrierIDCodeType = new WirelessCarrierIDCodeType();

?>
