<?php
// autogenerated file 17.11.2006 13:30
// $Id: XSLFileType.php,v 1.1.1.1 2006/12/22 14:38:58 gswkaiser Exp $
// $Log: XSLFileType.php,v $
// Revision 1.1.1.1  2006/12/22 14:38:58  gswkaiser
// no message
//
//
require_once 'EbatNs_ComplexType.php';

class XSLFileType extends EbatNs_ComplexType
{
	// start props
	// @var string $FileName
	var $FileName;
	// @var string $FileVersion
	var $FileVersion;
	// @var string $FileContent
	var $FileContent;
	// end props

/**
 *

 * @return string
 */
	function getFileName()
	{
		return $this->FileName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFileName($value)
	{
		$this->FileName = $value;
	}
/**
 *

 * @return string
 */
	function getFileVersion()
	{
		return $this->FileVersion;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFileVersion($value)
	{
		$this->FileVersion = $value;
	}
/**
 *

 * @return string
 */
	function getFileContent()
	{
		return $this->FileContent;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFileContent($value)
	{
		$this->FileContent = $value;
	}
/**
 *

 * @return 
 */
	function XSLFileType()
	{
		$this->EbatNs_ComplexType('XSLFileType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FileName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FileVersion' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FileContent' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
